### ISSUE TITLE
Working Demo

### ISSUE THREAD

**Issue by D3VONT3CH** [huytd/agar.io-clone#10]
Working demo hosted on openshift:
https://pillo-nibro.rhcloud.com/

**Comment by huytd** [comment]
Thank you so much!! :+1: 
Could you tell me the location of the server? I'm thinking to put a list of community's server from many location all over the world :D

**Comment by D3VONT3CH** [comment]
us-east / openshift

**Comment by IgorAntun** [comment]
Thanks!
