### ISSUE TITLE
Getting literally 2 FPS

### ISSUE THREAD

**Issue by themuddfamily2** [huytd/agar.io-clone#101]
I've tried multiple different servers, even the demo, Im pretty sure its due to my bad computer or the network usage, just thought I'd put this as a bug as I do not lag on agar.

**Comment by huytd** [comment]
Could you try it with the server on your localhost? Most of the lag (currently) are due to the connection to server.
You can check the connection speed with `-ping` command (enter it to the chatbox)

**Comment by themuddfamily2** [comment]
It is still something I believe should be worked on as it is kind of making the game useless unless playing on LAN.

**Comment by phadeb** [comment]
Same here.

**Comment by IgorAntun** [comment]
Closing this issue since the problem seems to be caused by #5, #188, etc.
