### ISSUE TITLE
[Bug] edible dots are created outside the level ( are unreachable)

### ISSUE THREAD

**Issue by fry-** [huytd/agar.io-clone#104]
I've tried the live demo on heroku eu server and noticed that these edible dots partwise are created outside of the layer/box where you can move in. This makes these edible dots uneatable, which causes confusion and less edibles in the game.

**Comment by huytd** [comment]
There is the same bug reported but has been closed. Did you try with the latest source?

**Comment by fry-** [comment]
I don't know, I just clicked on the "heroku eu" button for the demo ( https://agar-clone.herokuapp.com/ ).
The bug is in there, maybe this demo doesn't run on newest source? I have no clue :smile:

**Comment by huytd** [comment]
OK I see. Heroku EU use the very old code. I will check it :D

**Comment by IgorAntun** [comment]
Yeah this has been fixed at #86, which fixed this issue duplicate, #76.
