### ISSUE TITLE
[Feature Request] Visible game border

### ISSUE THREAD

**Issue by fry-** [huytd/agar.io-clone#105]
I hate the fact that in the original agarIO game, there are no visible borders. This causes trouble if you run away from another ball and suddenly your movement stops, because you reached the invisible end of the game.
I guess some thin line would be enough to make it visible and not distracting. Maybe this could be changed in the options, so players who want the "original feeling" could simply disable it.
This is low priority of course, but still would be nice at some point :stuck_out_tongue:

**Comment by themuddfamily2** [comment]
Agreed, I tried to add this myself but failed horribly as I have never used canvases before.

**Comment by giongto35** [comment]
I will try

**Comment by Buskcoin** [comment]
Would it be possible to make it a wrap-around world?
