### ISSUE TITLE
[Feature Request] Add a Leaderboard

### ISSUE THREAD

**Issue by jniles** [huytd/agar.io-clone#119]
It would be nice for each server to keep track of the rankings of its players (by mass) and display the top 5 largest players in the corner of the screen as a leaderboard.

Two possible implementations are:
1) The server maintains the list of players in a balanced tree (rather than an array as currently used), and rebalances whenever a player's mass changes.  This may potentially put some lag on the server side.
2) The client sorts the array of enemies every time it is received from the server.  This is cause lag on the client.

It would be nice to see who is king of the hill for the present game.  What do you all think?

**Comment by RemoveIt** [comment]
2. Is bad idea because giving info to every client about full game situation is big overhead (client should know only that which he can see). Option 1. Done 1 time per second seems to be good

**Comment by giongto35** [comment]
Option 1 is optimal. It will not put lag to server side because the computation for reshuffling is just O(log number of player, much smaller than current complexity of server side O(N) ) and it is just done whenever changes in mass happen.

**Comment by jniles** [comment]
@RemoveIt @giongto35 , thank you for the feedback!

I'll take a look at implementing option 1 when I get a chance.
