### ISSUE TITLE
Can't eat each other

### ISSUE THREAD

**Issue by 607nm** [huytd/agar.io-clone#12]
Hi,
we are using firefox on fedora and arch linux and we can not eat each other.
it does not matter who is larger, we can not eat the smaller one.
sometimes we can not even see each other

**Comment by D3VONT3CH** [comment]
sometimes i can eat, sometimes i can't

**Comment by 607nm** [comment]
eating foor is no problem

**Comment by huytd** [comment]
Hi, thank you for the report. I will check again. 

But there are an untold rules in the source code :trollface: 
- You can't eat the newbie (who didn't eat any food)
- Your mass (amount of food eaten) must be 5 food larger than victim's mass to eat him

May be that's why you can't eat :D

**Comment by D3VONT3CH** [comment]
us-east / openshift

**Comment by IgorAntun** [comment]
Closing it since it has been explained.
