### ISSUE TITLE
Deploy to Heroku not working

### ISSUE THREAD

**Issue by mblode** [huytd/agar.io-clone#125]
I am attempting to deploy this game to Heroku but it fails saying "socket.io-client#1.3.5 client/bower_components/socket.io-client
remote:        module.js:338
remote:            throw err;
remote:                  ^
remote:        Error: Cannot find module '/tmp/build_3e4006a7a369453a3cb85accf7e6bf96/node_modules/gulp/bin/gulp.js'"

Could someone help me? I've never done this before.

**Comment by themuddfamily2** [comment]
You need to npm install.

**Comment by mblode** [comment]
I needed to move the devDependencies to Dependencies and create a Procfile for the project.

**Comment by artuross** [comment]
Actually, this is wrong, npm scripts should be updated and `npm start` should be an alias for `node server/server.js`

**Comment by mblode** [comment]
Yes that is what I did
