### ISSUE TITLE
Gulp crash leaves server running

### ISSUE THREAD

**Issue by danprince** [huytd/agar.io-clone#127]
Leaving this here with the hope that someone who knows Gulp better than I will see it.

I'm currently working on the ES6 + Browserify rewrite (es6-refactor branch) and whenever `gulp watch` throws an error it prints it and then exits, but it leaves the server running in the background.

This means that when running `gulp watch` again to get the watcher started, the server tries to listen and always fails because there's already the old server running on 3000 (`netstat -tulpn`, `kill -9 pid` etc).

Pretty sure it should be possible for Gulp to throw an error without exiting? Otherwise it would be good to not start the game server if there's already something running on 3000.

Also, not sure why the build process is trying to find modules in the `bin/` directory. That's what's causing these crashes in the first place. Error below:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module './chat' from '/home/dan/dev/fork/agar.io-clone/bin/client/js'
    at /home/dan/dev/fork/agar.io-clone/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/dan/dev/fork/agar.io-clone/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/dan/dev/fork/agar.io-clone/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/dan/dev/fork/agar.io-clone/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

```

**Comment by danprince** [comment]
It's also probably worth pointing out that the first thing I tried was moving the transform away from the pipe, as shown in the [gulp browserify recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-transforms.md).

**Comment by RemoveIt** [comment]
Ok I'm looking at it

**Comment by RemoveIt** [comment]
@danprince  
![capture](https://cloud.githubusercontent.com/assets/8374421/7936136/19f3c84e-0937-11e5-9646-6a845b16eb6e.PNG)

**Comment by RemoveIt** [comment]
>Also, not sure why the build process is trying to find modules in the bin/ directory

build process if using `/bin` for nodemon in `run` task
every other task is outputing to `/bin`

**Comment by danprince** [comment]
Cheers. Added to my local branch.

I know what `/bin` is being used for, but it's browserify throwing an error, saying that it can't find a module in the bin dir. Browserify should only care about the client/js dir.

**Comment by danprince** [comment]
`gulp build` works fine, but `gulp watch` does something funny with Browserify.

**Comment by RemoveIt** [comment]
i think it it is internal browersify/babelify stuff
propably this crap work like this:
1. babel outputs common.js modules to bin dir
2. then browersify is looking at this folder but hey there is missing module and you are getting this error

**Comment by danprince** [comment]
But browserify isn't responsible for any watching, it knows that it's source comes from `./client/js/games.js`, no matter what triggers the watch, that is where it should try and find it's modules relative to.

**Comment by RemoveIt** [comment]
`gulp watch` are just runnig `gulp build` when files in client and server folders are changing.
Nodeamon form `gulp run` (which is also started from `gulp watch`) is watching bin folder and is restarting when files are chaging there.

**Comment by RemoveIt** [comment]
nvm I'm wrong about how browersify/babelify work
I'll look at it later but tell me @danprince if everything is working well for you?

**Comment by danprince** [comment]
Yeah, everything's awesome apart from this error.

Just resorting to having `gulp run` in the background and running `gulp build` manually, which is fine for now.

**Comment by RemoveIt** [comment]
@danprince after my fix too?

**Comment by danprince** [comment]
The fix stops `gulp watch` from crashing when it errors, but the browserify error is still there and it doesn't create a build because of it.

**Comment by RemoveIt** [comment]
![capture](https://cloud.githubusercontent.com/assets/8374421/7937598/35ba39d2-0941-11e5-8db6-075888cc5178.PNG)
Maybe now it is working

**Comment by IgorAntun** [comment]
Has this been fixed?

**Comment by IgorAntun** [comment]
Closing it since it appears to have been fixed.
