### ISSUE TITLE
[Opinions Wanted] Coding Style - Poll

### ISSUE THREAD

**Issue by IgorAntun** [huytd/agar.io-clone#132]
Hey, I think it's about time we decide a definitive coding style for this project. I think we could use this issue as some form of "poll" to vote.

**My vote goes for:** [Airbnb Style Guide](https://github.com/airbnb/javascript)
**Because:** I think it's pretty clean and *very* readable.

**Comment by artuross** [comment]
Sounds good, I'd also add JSCS and jshint rules.

**Comment by jniles** [comment]
I also like Airbnb's style guide.  It has my vote as well. :+1:

**Comment by huytd** [comment]
:+1:

**Comment by JoeMattie** [comment]
Another vote for Airbnb's style guide.

**Comment by IgorAntun** [comment]
Ok, 5 votes for Airbnb code style so far. Let's use it :)
I can refactor the code later today and update the README.md about it.
Thanks everyone!
