### ISSUE TITLE
[Question]: Should we allow empty nicks?

### ISSUE THREAD

**Issue by jniles** [huytd/agar.io-clone#140]
Currently, players can simply click to begin and have an empty nick.  This doesn't affect the game play at all, but I wonder if we should enforce nicknames for players.  What do you all think?

**Comment by hunterpl** [comment]
Hello jniles

Yes just in case. Special characters will be allowed?

**Comment by IgorAntun** [comment]
I'd limit to alphanumeric only (a-z/A-Z/0-9), and allow empty nicks yes.
