### ISSUE TITLE
Start/Stop server script.

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#143]
Hello Dear Developers

Can you build script shell with start / stop function for dedication servers, because now the server work only when start command "npm start" in background and when I leave SSH the server stop working. I would like have a script with start and leave my SSH Putty console without stopping server.

Edit: Please add additional folder logs and in this folder put separated logs files with every start titled with time. I think that would be a good idea.

Best Regards
Mateusz

**Comment by IgorAntun** [comment]
Good idea. I'm sure someone here can make it happen.
In the meantime, remember you can always use `forever` or the command `screen` to keep your server running after exiting the SSH client ;)

**Comment by hunterpl** [comment]
Hello Dear Igor

I won't start with screen due I can not read the logs, much better looks if We have folder logs and nice script start / stop or debug mode.

**Comment by IgorAntun** [comment]
Good point. I agree.

**Comment by themuddfamily2** [comment]
Surely making it log everything to console + console.log would fix this?

**Comment by IgorAntun** [comment]
@themuddfamily2 That wouldn't save the logs. His point is actually writing the logs to a file, which I agree on.

**Comment by kbariotis** [comment]
@hunterpl running a Node app in a dedicated server requires to create a service of this app. This is not an issue of the app itself I believe.

**Comment by hunterpl** [comment]
I would make additional request for the script, if server is down coz some error appeared, so the error output should be saved into folder logs and after this action, server should be auto-restarted by the script due you can not be 24/h on your computer.

**Comment by JuhQ** [comment]
[PM2](https://github.com/Unitech/pm2) has all the features requested here.
Just run `pm2 start server/server.js` and then you can follow the logs with `pm2 logs`

**Comment by IgorAntun** [comment]
@hunterpl I suggest you using PM2, as @JuhQ suggested above.
