### ISSUE TITLE
Let newbies be eaten?

### ISSUE THREAD

**Issue by shakdoesgithub** [huytd/agar.io-clone#15]
I think newbies should be allowed to be eaten. I feel it makes the game more fun when you start you have to work your way up

**Comment by huytd** [comment]
but it will not fun if you die immediately because some guy standing at your spawn point :D that's the problem

**Comment by IgorAntun** [comment]
I think it should stay as it is. Newbies must eat at least 1 food to be able to get eaten.

**Comment by IgorAntun** [comment]
@huytd what do you think?

**Comment by huytd** [comment]
I agree with the current gameplay :D

**Comment by IgorAntun** [comment]
Closing it then, but thanks for the suggestion @shakdoesgithub :)
