### ISSUE TITLE
client side border bug

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#154]
Hello dear developers

i found the bug with stuck on the zone I can't move and get a piece of cake even i see it. The borders server is a different than client side + i can't see the others players if that bug appear. Thanks for fixing it later.

Best Regards
Mateusz

**Comment by Crasha** [comment]
I can confirm this. Getting stuck in the border, unable to get out. 

Possibly linked to this https://github.com/huytd/agar.io-clone/commit/e42aaf27e770bb8806aa09edf83f052ced539948

**Comment by IgorAntun** [comment]
@Crasha this issue is older than this commit. By the way, can you two please elaborate a bit more on what specifically causes the bug and what it consists of?
Thanks :)

**Comment by Crasha** [comment]
@IgorAntun Oh right! I've only noticed it doing it when the coloured border was committed. All you have to do is move your "cell" into the border and you'll become stuck. Not sure if it happens all the time but it definitely does it 9/10.

**Comment by IgorAntun** [comment]
Weird, never noticed that while testing the new visible border.. :\

**Comment by IgorAntun** [comment]
Should be solved.
