### ISSUE TITLE
Crash when clicking on chatbox and moving mouse off

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#158]
I've discovered an issue in which if you move your mouse over to the chat box to type a command or message, and then move the mouse off to play like normal, there seems to be some major delay and the browser seems to try and lock up for some reason.

**Comment by Crasha** [comment]
To reproduce, I've also noticed when you use the scroll wheel too.

I think the scroll wheel should zoom in and zoom out the game.

**Comment by abalabahaha** [comment]
Cannot reproduce. What browser are you using?

**Comment by Crasha** [comment]
Chrome. Just scroll when your moving around and it will become unplayable.

**Comment by abalabahaha** [comment]
Try updating everything. It works perfectly fine for me, tested on Chrome and latest clone with no issues. Can you check Chrome console for errors and put them here?

**Comment by IgorAntun** [comment]
Does that still happen?

**Comment by abalabahaha** [comment]
I cannot reproduce this XD

**Comment by IgorAntun** [comment]
Please re-open it if it happens to come back.
