### ISSUE TITLE
web browser issue

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#159]
Hello Developers

Web browser Google chrome make lag as hell over 5k ms ping when on the FireFox i have below 49 ms on the same server. Can you check that issue?

Best regards
Mateusz

**Comment by IgorAntun** [comment]
I haven't noticed that. Can anyone else confirm that?

**Comment by abalabahaha** [comment]
After a few seconds of playing, Safari starts to lag and/or crash. I don't see any difference between Chrome and Firefox.

**Comment by IgorAntun** [comment]
Could you please try debbuging it?

**Comment by abalabahaha** [comment]
#158 could be the reason for the lag Chrome users are having.

**Comment by IgorAntun** [comment]
Is it still happening?

**Comment by abalabahaha** [comment]
Weirdly enough, I can't reproduce this anymore.

**Comment by IgorAntun** [comment]
Ok, just re-open it if it happens again then :)
