### ISSUE TITLE
Increase in size gradually, and include more food

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#160]
I think if we increase the amount of food spawned by a lot and then gradually increase the size of your "cell" instead of "+1" for example, then it will act more like the original game. 

At the moment, you can become very large quite easily in a matter of minutes, whereas on the original game, it takes a while to get to that point due to the incrementation in size. 

I think as you get bigger, the incrementation of your size decreases slowly so it takes a lot more food to get bigger etc.

**Comment by IgorAntun** [comment]
I don't think it's because each food increases you more, it's just that it seems that on Agar, you lose X% of your mass every 5 seconds, so as you get bigger, you need more and more food to compensate that loss and get larger (profit of that compensation)

**Comment by Crasha** [comment]
Oh really? I never noticed that decrease in mass. Is that possible with some sort of client side timer? e.g.. 

var PlayerMass = CurrentMass - 0.1;

**Comment by IgorAntun** [comment]
Yeah it's like you spend energy on moving, it also helps balancing the game so huge players can't just sit there forever.

I don't think a client timer would be enough, since players could bypass it. That should be handled by the server.

**Comment by fry-** [comment]
Yes, you constantly lose mass, no matter how big you are (exept you are smallest initial bubble size). To check this out on agar.io, go to the settings (little gear symbol) before you start and tick the "show mass" option. now play the game and look how your mass constantly decreases, the bigger you get the faster the mass is lost. So it is something like @IgorAntun  said :P For cloning the exact same effects, some research has to be done on agar.io.
![Screenshot](http://i.imgur.com/lFtIkqy.png)

**Comment by JoeMattie** [comment]
If I understand correctly, the mass in an agar level is constant.  All players experience attrition, where their mass is slowly redistributed as food (krill, skittles, whatever) at a rate having mass as a factor, thus large players lose mass faster.
