### ISSUE TITLE
Mouse actions

### ISSUE THREAD

**Issue by safaacar** [huytd/agar.io-clone#161]
hi programmer , Mouse operations are not working  .games without moving the mouse does not work .

**Comment by IgorAntun** [comment]
Is that also happening to anyone? It's working just fine for me, no issues at all.

**Comment by safaacar** [comment]
I took the same files again. I updated . still it did not improve. What could be the problem ? your think ?

**Comment by safaacar** [comment]
can you help me please ? :/

**Comment by themuddfamily2** [comment]
No one else is getting this issue, try actually deleting all the files and cloning again, check the network tab in chrome if you aren't using it on localhost

**Comment by hunterpl** [comment]
@safaacar Do you use the web browser Google chrome? please try on FireFox. If you have this issue like I have, please see the issue #159

**Comment by safaacar** [comment]
Hi First I thank you for your answer , i am trying firefox but dont working . if you want see : http://www.2bucuk.com:3000/ . current files

**Comment by hunterpl** [comment]
@safaacar please make a following guide:

1. Stop the server
2. Download files from: https://github.com/huytd/agar.io-clone as a ZIP.
3. Overwrite files on your server.
4. Execute command: npm install && npm update && npm start
5. Server should be started.
6. Check server and report here.

**Comment by safaacar** [comment]
I'll try them. and I will write to you . thanks for answer

**Comment by IgorAntun** [comment]
Closing issue since it seems to be abandoned.
