### ISSUE TITLE
Clan wars

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#167]
Hello Dear Developers

What do you think about introduce in the future "clan wars"?
Each clan could have a skin or unique group for character, at this moment like you saw on the youtube, some youtubers have own group and the members just add some sign #BH [$] etc on the end to be friendly to the other if someone is in the same group.

From the client side in home page every one should be able choose from the selector his group to mark him self where he/she belongs, after join to the server, see the skin of the group, we could have create popular default skins like on agar.io are like earth etc...

Example Menu:

nickname: [     ] [ a-z A-Z 0-9 ]
group / clan: [     ] - if choose the group of clan/group, someone can't select the skin due of unique skin signed for the clan/group.
skins: [     ] - only available for neutral players.
server: [     ] sub-servers instances.

Best Regards
Mateusz

**Comment by IgorAntun** [comment]
Thanks for the suggestion, but someone already created an issue for Team Mode: #66 :)
In order to keep the discussion in a single issue, I'm going to close this one so we can focus on the older issue :)
