### ISSUE TITLE
Installation Guide & System Requitments

### ISSUE THREAD

**Issue by Kagetane** [huytd/agar.io-clone#171]
Hallo,
my name is Hiruko Kagetane
i want asking you waht's i need to run agar.io clone in my own website
i that i need vps hosting or other ?
and i want asking about installation guide
if you can please make a full tutorial with image or a video :)
Thanks for your script :)

**Comment by themuddfamily2** [comment]
VPS hosting is ok if you want a private server with you and your friends, I suggest a dedicated server or a big VPS if you want to make it public.

To install you can google most steps.

**Comment by Crasha** [comment]
All you need to do is install npm and nodejs via "apt-get" if you're on Debian or Ubuntu based systems. Then run "sudo npm install" while inside the folder that was downloaded via the git clone on the repository.

**Comment by safaacar** [comment]
How is written at the entrance of the site is changed ?

**Comment by IgorAntun** [comment]
You can use nginx or apache or whatever you use to redirect `www.yoursite.com/agar` to `127.0.0.1:3000`, try google'ing "node.js proxy on [apache/nginx]"

**Comment by Kagetane** [comment]
i will buy a dedicated server 
but i want you to make a video guide how to install it from begin use my dedicated server 
i want make it public and if you want you can add it into your demo :)

**Comment by MrJerB** [comment]
@Kagetane, the installation process is not complex enough to require a video. It is the same as deploying most other Node applications. :smile:

Depending on your dedicated server's OS, the steps recommended by @Crasha would require the following command-line entries:
```
sudo apt-get update
sudo apt-get install nodejs
sudo apt-get install npm
```
Then you clone this repository onto the server and run the following command within the repository directory to download all the project's dependencies:
```
npm install
```

If you're not hosting anything else, you won't even need a webserver to provide the proxy suggested by @IgorAntun and then if you are, lots of information is available to help set that up.

**Comment by Kagetane** [comment]
:3 is that any one here can tell me how to install it on vps using SSH Putty ?
from begin please 
OS : CentOS

**Comment by Buskcoin** [comment]
You could use AWS instead. It's pretty staight forward.
* Download the github repo
*  Dl and install dependencies 
      * `sudo apt-get update`
      * `sudo apt-get install nodejs`
      * `sudo apt-get install npm`
      * `npm install`
* Once it's built, zip the files into a folder
* Sign up for amazon aws(freeish for a year). 
* Go to http://aws.amazon.com/elasticbeanstalk/
* create new node.js web server on elastic beanstalk
* upload zip folder and see if it works. Let me know if it doesn't.

**Comment by IgorAntun** [comment]
Any following questions or should I close this issue?

**Comment by safaacar** [comment]
I did write operations in the message. but I can not run .

**Comment by IgorAntun** [comment]
Closing this since it seems to have been abandoned.
