### ISSUE TITLE
Game architecture wiki

### ISSUE THREAD

**Issue by dumb-questions** [huytd/agar.io-clone#172]
Sorry to ask here, did not find a gitter chat or something equivalent. But I would lile to know how the graphics were made that accompany the game architecture wiki. :O

**Comment by themuddfamily2** [comment]
https://gitter.im/huytd/agar.io-clone

**Comment by dumb-questions** [comment]
Thanks, now I also see the gitter badge, weird. I will close this issue and ask in the chat.

**Comment by IgorAntun** [comment]
@dumb-questions See #74

**Comment by dumb-questions** [comment]
Thanks @IgorAntun it seems yesterday was not my day, hehe.
