### ISSUE TITLE
Binary Protocol

### ISSUE THREAD

**Issue by neslinesli93** [huytd/agar.io-clone#177]
Help wanted for fixing a bug in my (very first and very bad) attempt to creating a binary protocol for message exchange. I think this can make the game way more reactive over non local networks and improve the overall gaming experience, making it more similar to the original game.
This is a very small (but necessary) step, that had to be done sooner or later. For more details, look at #176

**Comment by IgorAntun** [comment]
I think we could move this discussion to #5, to avoid creating duplicates :)
