### ISSUE TITLE
good idea for new mod for this game

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#180]
Hello all

Do you remember the game Warcraft the frozen throne? and the mod called "Mad Balls Arena"
There is a YT video clip: https://www.youtube.com/watch?v=FXlQ1Ih1szs have fun with watching.

We could introduce the mad balls arena into the game:
- normal ball
- fire ball
- gravity ball
- ice ball

that mod could be uses for DM, TDM and make much more fun instead.

Best Regards
Mateusz

**Comment by Azeranth** [comment]
That seems a bit off the idea of Agar.io but it is nice. I had thought of something perhaps along the lines of Bots that would be passive and just roam around perhaps we could make them dangerous like moving viruses

**Comment by justmemaarten** [comment]
Does this game have the green Virusses???

**Comment by IgorAntun** [comment]
I'm not sure if this should be a issue at all. Closing it since it does not contribute to the general purpose of this project. Maybe you could have it in a fork, though :)

And @justmemaarten no, not just yet, but it is in the works :)
