### ISSUE TITLE
Someone help me with the stup

### ISSUE THREAD

**Issue by justmemaarten** [huytd/agar.io-clone#189]
Can please someone help me with the setup NPM wont install get errors all over the place,....

**Comment by Buskcoin** [comment]
What OS are you using? Copy your errors into google and see what they are. It's likely someone else has had the same problem setting up.

**Comment by justmemaarten** [comment]
https://www.dropbox.com/s/qnsx67acdu8upg4/errorcodeinstallnpm.jpg?dl=0 this is the error

**Comment by Buskcoin** [comment]
You are in a folder called "Administrator". Are you sure you're running this command in the right folder? Make sure you clone the github and you are in the right folder when you run the command. It might be called "agar.io-clone". Or whatever you save it as.  Just you `cd <your agar clone here>`

**Comment by justmemaarten** [comment]
How do i need to clone etc? can you please help me out and make a TUT from beginning (like github setup fith nodejs) cause im a beginner man :S idk how this work @Buskcoin

**Comment by Buskcoin** [comment]
Just download and extract the zip.
![image](https://cloud.githubusercontent.com/assets/6021332/8046021/8340c0a4-0dec-11e5-988e-dbf4276f8207.png)

**Comment by IgorAntun** [comment]
@justmemaarten did that work for you? :)

**Comment by justmemaarten** [comment]
@IgorAntun Yeah the clone worked, but i cant pass the freaking install of npm... please someone install it for me add me on skype or something "Owner_death1" <--- skype name. Thanks for helping!

**Comment by IgorAntun** [comment]
Take a look at http://blog.npmjs.org/post/85484771375/how-to-install-npm

**Comment by IgorAntun** [comment]
Closing this as it seems to have been abandoned.
