### ISSUE TITLE
Viruses

### ISSUE THREAD

**Issue by Azeranth** [huytd/agar.io-clone#194]
I have started coding the viruses into the game so with the server side I went into config and saw no way during the heart beat to tell if the target is a virus or a food or player, am I missing something or do I need to add that?

**Comment by themuddfamily2** [comment]
You could add it to the users list and then do users[e].isVirus == true then the current hit testing code will work.

**Comment by Azeranth** [comment]
I had set it up as its own list and was going to have it check in the heart beat if the collision has occurred and if it had to steal half the players mass but to do that it was necessary to know if the player had encountered a food or virus and there is nothing in food to tell if it is a food or not so should  i add an isFood=Ture and an isVirus=False to food and the opposite to Virus

**Comment by Azeranth** [comment]
or maybe a type

**Comment by themuddfamily2** [comment]
In the actual agar they use isVirus, http://agar.io/main_out.js?531

**Comment by Azeranth** [comment]
is that a function that checks or is it a property

**Comment by IgorAntun** [comment]
Hey, in order to avoid duplicates, could we please move this discussion to #25 so people can find details about Viruses in a single place?
Thanks! :)

**Comment by Azeranth** [comment]
Sorry I don't realize there was already an issue on the viruses
