### ISSUE TITLE
Hit test: NaN ± 10

### ISSUE THREAD

**Issue by 607nm** [huytd/agar.io-clone#2]
When starting a game i can see my red dot, but as soon as i move my cursor the server says "Hit test: NaN ± 10" and the food dots begin to appear.

**Comment by IgorAntun** [comment]
Hmm true that. I'll check what's up with that.

**Comment by IgorAntun** [comment]
It's working just fine here... Have you changed anything in the source code?

**Comment by Longer** [comment]
Same problem was.

Patch for fix:
```
diff --git a/index.html b/index.html
index 6d3b79c..11d8283 100644
--- a/index.html
+++ b/index.html
@@ -164,7 +164,7 @@ canvas {
 	}	
 
 	function gameInput(e) {
-		target.x = e.x; target.y = e.y;
+		target.x = e.clientX; target.y = e.clientY;
 	}
 
 	window.requestAnimFrame = (function(){
```

**Comment by huytd** [comment]
It should be browser problem. I know the mouse move event data are different between Chrome, Firefox and Safari, IE,... 
Which browser you are using?

**Comment by huytd** [comment]
Thank @Longer for the fix. I applied your patch!

**Comment by 607nm** [comment]
Thank you, the game is now working in firefox, awesome project
