### ISSUE TITLE
Lag Problem

### ISSUE THREAD

**Issue by nanoeray** [huytd/agar.io-clone#203]
hi i install the script on windows vds (2gb ram 2x core 100mbit network speed). i login the game no problem but im getting 15000-20000ms ping on another player login. so im getting a very big lag on 2+ players. how can i fix this

**Comment by IgorAntun** [comment]
Hey, that could be caused by #159, could you please comment on there with the specifics of the browser you're using?

Also I'm going to close this issue since it's caused by #82 and is related to #5.

**Comment by nanoeray** [comment]
im using google chrome one player no log but 2+ player very very big lag

Date: Thu, 11 Jun 2015 19:02:23 -0700

**Comment by nanoeray** [comment]
anyone else?

**Comment by abalabahaha** [comment]
As Igor said, this is probably a duplicate of #159 , comment on there instead.
