### ISSUE TITLE
Moving too slowly / Also when growing

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#204]
I've just updated my master copy with the latest release on github and I've noticed that the cell moves way to slowly when starting off. I changed it to 12 and it was more Agar.io like then, however when eating, the speed decreases too rapidly. This means when you're double your size you start off with, which isn't big at all, your speed is as if you're one of the huge people in the lobby.

**Comment by Crasha** [comment]
If you increase the speed of the cell when starting off, I think the slowing down will be fine. I think it's just that since you start off very slow, it seems like it is slowing down too fast when eating.

**Comment by abalabahaha** [comment]
The speed does decrease much more rapidly than the original

**Comment by Buskcoin** [comment]
you can adjust this in the config by increasing slowdownlog.

**Comment by abalabahaha** [comment]
Changing that makes the game go too slow/fast. It's the rate of slowdown that's off.

**Comment by Buskcoin** [comment]
You're right. That shouldn't happen. I sent in a pr to fix it and also adjusted the slowing when growing. You should be able to adjust it now. It's called "slowBase" in the config.

**Comment by abalabahaha** [comment]
This has been resolved.
