### ISSUE TITLE
New Demo C9.io

### ISSUE THREAD

**Issue by D3VONT3CH** [huytd/agar.io-clone#21]
https://agar-io-clone-d3vont3ch.c9.io/

this works like a charm

**Comment by IgorAntun** [comment]
What's the location?

**Comment by D3VONT3CH** [comment]
i don't know

**Comment by huytd** [comment]
Do we need to login? It asked me to login first.

**Comment by D3VONT3CH** [comment]
serious?

**Comment by IgorAntun** [comment]
Yeah. Cloud9 apparently asks for an account.

**Comment by huytd** [comment]
I added your server to `README.md`, @D3VONT3CH  :D

**Comment by huytd** [comment]
@D3VONT3CH Do we need any config to run it on C9 (like Heroku, OpenShift)? If need, could you make a patch to put these config in `server.js` please? :D

**Comment by D3VONT3CH** [comment]
try now, was my mistake, sorry

**Comment by D3VONT3CH** [comment]
no, is the same code.

**Comment by huytd** [comment]
great! it's work fine now!
