### ISSUE TITLE
Mouse out of window handling

### ISSUE THREAD

**Issue by abalabahaha** [huytd/agar.io-clone#215]
In the original, moving the mouse pointer out of the window causes you to keep moving in the direction the mouse was last in. In here, though, there is code that stops the player when the mouse is off the screen. Is this intended?

**Comment by IgorAntun** [comment]
Yes this was intended (as of #44), do you think it would be better to revert it?

**Comment by abalabahaha** [comment]
It really depends on the situation... Sometimes it's useful to keep it moving, and sometimes it's not. Maybe add it as a setting?
