### ISSUE TITLE
Weird icon transitioning once hit the right border

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#220]
So I've noticed this strange icon transitioning from smaller to bigger, and then from bigger to smaller over and over again. You need to get quite big in order to start seeing it. I attached a picture showing the differences. I found out that this only happens when you hit the right wall, so you start transitioning flat as if your cell is moving up/down the wall.

![icon transition](https://cloud.githubusercontent.com/assets/4403436/8266700/cbc189d4-1734-11e5-8866-5dbdcdc679ff.png)

I circled the icon in this photo so you can see what I'm on about;

![icon transition 2](https://cloud.githubusercontent.com/assets/4403436/8266703/f2bc7256-1734-11e5-9d25-0514b4ab7a75.png)

**Comment by abalabahaha** [comment]
That's the wiggle effect that it makes when part of the cell goes into the wall... Yeah probably should turn it off when the cell's not in the wall lol.

**Comment by abalabahaha** [comment]
Fixed, will be in my next PR.
