### ISSUE TITLE
Losing Mass Cell per second as feature

### ISSUE THREAD

**Issue by hunterpl** [huytd/agar.io-clone#224]
Hello Dev!

Can you build the script which can calculate losing mass per second? because on agar.io the cells losing their mass per second and if you are really big cell, you will loosing quicker and  much much more mass. Do We have point when map is resetted? at Agar.io you have to reach goal 20k points as one cell.

Best Regards
Mateusz

**Comment by abalabahaha** [comment]
If nobody does it by the next time I start working, I'll put this in my next PR. Does anybody have an estimate of the rate of mass loss?
