### ISSUE TITLE
Modify quantity of food spawn

### ISSUE THREAD

**Issue by Crasha** [huytd/agar.io-clone#225]
So I adjusted a while ago how much food was spawned, and it turns out that may be too much. I looked at the config on the server side and saw that the variable has been removed to alter how much food can be spawned. Can you tell me the file name and line number for what I need to look at to modify this? It's changed a lot since I last looked at the code.

I'm just trying to get it as close as possible to the original game imo.

**Comment by Buskcoin** [comment]
You can adjust the food amount through gameMass but I think that also brings down your Max mass

**Comment by abalabahaha** [comment]
I'll see if I can do this in my next PR.

**Comment by Crasha** [comment]
Thanks.
