### ISSUE TITLE
Code quality enforcing

### ISSUE THREAD

**Issue by JuhQ** [huytd/agar.io-clone#255]
It seems that a lot of pr's coming now doesn't seem to be following good enough coding standards.
There's `gulp lint-client` and `gulp lint-server` commands for linting the code.

How can we enforce this?

Let's open discussion about code quality on this thread.

**Comment by JuhQ** [comment]
An example: I just fetched the upstream and client had 17 errors and server 6 errors.
This is code which has been merged to master. This is bad.

**Comment by jniles** [comment]
Did this get fixed in #257?

**Comment by IgorAntun** [comment]
Should be fixed, yes.
