### ISSUE TITLE
Add leaderboard

### ISSUE THREAD

**Issue by siddharthlohchab** [huytd/agar.io-clone#259]
It is missing the most important thing a LEADERBOARD.
I hope someone will work upon it!

**Comment by ama291** [comment]
It has a leaderboard, the most recent demo is online at: http://agar.ts3bahu.com:3000/ and on the top right, the players are ranked in order.

**Comment by IgorAntun** [comment]
Yeah this is a duplicate of #119, which was implemented and closed with #221 :)

**Comment by siddharthlohchab** [comment]
Thanks!!
