### ISSUE TITLE
Cannot connect via the client on OSX

### ISSUE THREAD

**Issue by ama291** [huytd/agar.io-clone#260]
I'm running OSX Yosemite and using Chrome. The online demos work fine for me but when running the server locally, I can access the page and enter my name but the game never loads when I press the play button.

**Comment by Buskcoin** [comment]
I had a similar problem with the latest version. I just cloned the repository again and it worked. Check what error you're getting with inspect elements in chrome. Use npm install and npm start. Im using ubuntu so I dont think it's your os.

**Comment by IgorAntun** [comment]
Yeah first of all try deleting the your directory and cloning it again, then run `npm install` and `npm start`, let us know if it still doesn't work after that :)

**Comment by ama291** [comment]
Awesome, it worked, thanks! I figured it out, ```node server/server.js``` doesn't work anymore because it doesn't start Gulp. The readme says you can start the server using either.

**Comment by IgorAntun** [comment]
Good catch, I'll update it!
