### ISSUE TITLE
Problem in Heroku

### ISSUE THREAD

**Issue by makanenzo10** [huytd/agar.io-clone#262]
I attempted to install this onto Heroku with the button you guys have on the information section, but then upon deployment I get an error and apparently it is part of the app.json section. If you guys can check and tell me if there is any issue on my side or just something messed up. :)

Log: http://pastebin.com/raw.php?i=T3uasseJ

**Comment by abalabahaha** [comment]
I believe #261 should have fixed this?

**Comment by IgorAntun** [comment]
I think it should, yes. Not sure though.

**Comment by makanenzo10** [comment]
That worked ;) Thanks! Might want to also add it to the official files xD

**Comment by abalabahaha** [comment]
@makenenzo10 That fix was merged, but after you tried installing.

**Comment by IgorAntun** [comment]
Glad it worked :)
