### ISSUE TITLE
Fire a food

### ISSUE THREAD

**Issue by huytd** [huytd/agar.io-clone#27]
Press W or something to fire yourself as a food. To feed other player or virus.

**Comment by IgorAntun** [comment]
What would be the use case of feeding other player or a virus? Isn't splitting yourself (space) enough?
I can see that being abused to be able to eat newbies, also.

**Comment by Netifriik** [comment]
@IgorAntun feeding a virus is a good way for smaller cells to be aggressive against the bigger cells. Once at a certain cell size a virus will split your cell into smaller ones if hit.

**Comment by IgorAntun** [comment]
@Netifriik hmm I see, good point.

**Comment by huytd** [comment]
Split will make yourself separate in to many pieces. But fire will make yourself smaller.
They're different and will make the gameplay more fun. 
I think we can follow the original Agar.io game or we can create some other useful skill for our game.

**Comment by Ariamiro** [comment]
Or we can do both.

**Comment by IgorAntun** [comment]
@Ariamiro there **will** be both, splitting and firing food ;)

**Comment by francisco-maciel** [comment]
The input focus is on the chat when loading the page, meaning pressing W is writing in the chat rather than firing the food. This will probably happen again once the split feature is ready. Shouldn't the default focus be on the game window?
