### ISSUE TITLE
mouse and touch ?

### ISSUE THREAD

**Issue by matrixreal** [huytd/agar.io-clone#271]
hi,
is there a way to add touch object ?
i'm using ejecta and i would like to use this clone and ejecta wrapper (as webview)
but i'm not sure if the touch action will work !!!

**Comment by abalabahaha** [comment]
Well I mean I suppose touch events / accelerometer / joystick could be added

But isn't this still too laggy and bandwidth/resource-intensive for mobile devices?

**Comment by matrixreal** [comment]
no, i don't think so ...

**Comment by matrixreal** [comment]
i have test it on phone it's wonderful it work fine .... i hope you can add touch features :dancer:

**Comment by matrixreal** [comment]
joystick mouvement

**Comment by matrixreal** [comment]
yes the circle is following only when you tap the screen (it change direction to the position you ta on it)
it will be great if you add something like if you keep touching it will follow the tap position
like joystick mouvement
thanks

**Comment by abalabahaha** [comment]
Ok I think that's a touchmove, will look into it

**Comment by matrixreal** [comment]
the mouse object is working good on pc browser
however when we lunch it from a phone device
you have to touch and release to make the dot change direction !!! is it clear or maybe my english is bad
i hope that you add something like when we touch the screen and keep touching with changing direction with our hand the dot follow that mouvement ...:D

this is great project ... i will post it in my forum if you like

**Comment by IgorAntun** [comment]
@matrixreal We understood it perfectly, @abalabahaha will probably see if he can add this feature. Thanks :)
And yes, it would be much appreciated if you could share this project in your forum!

**Comment by matrixreal** [comment]
@IgorAntun 
we would like to implement this project to a mobilde device application
do you think that is possible ?

**Comment by IgorAntun** [comment]
It certainly is @matrixreal . As long as the app communicates to the socket server, everything should work just fine.

**Comment by matrixreal** [comment]
@IgorAntun 
that's okay
the 2 only things i need to deploy it to an app are:
1-disable chat
2-solve the problem with the touch event
i will try to put it on iframe if you don't see an incovenient !!!
thanks for reply

**Comment by abalabahaha** [comment]
@matrixreal Can you confirm if #277 fixed this?

**Comment by matrixreal** [comment]
@abalabahaha 
still same ... it work only when you touch on different place and then the dot do to the direction you touch
still not work like joystick (keep pressing)
also chat mode is always enabled and

**Comment by abalabahaha** [comment]
@matrixreal Are you sure you updated your local version? In your console, do:
```
git pull
npm install
gulp run
```

**Comment by matrixreal** [comment]
I just lunch the 
agar.ts3bahu.com:3000

Envoyé de mon iPhone

**Comment by abalabahaha** [comment]
I'm getting ping upwards of 120 seconds, so I can't really test right now... Can anyone else attempt to check mobile support?

**Comment by matrixreal** [comment]
I told you i just try it from 
agar.ts3bahu.com:3000
And the problem is still there or maybe you have not update the serveur of agar.ts3bahu.com:3000?
Thanks
This project Will got success Like original ;)
Envoyé de mon iPhone

**Comment by abalabahaha** [comment]
Oh yeah as of the recent update, every server on the list on the README is outdated. When #276 is implemented, it would be possible to have the server list update itself.

**Comment by matrixreal** [comment]
Ok so we have to wait until update ?
And can i create my own serveur with this project?
I have good internet windows serveur 

Envoyé de mon iPhone

**Comment by Buskcoin** [comment]
Yes, please do.

**Comment by matrixreal** [comment]
@abalabahaha 
@IgorAntun 
thanks a lot works perfect ... chat is desabled .... and touch event work perfect 
just it lag a lot is it about serveur ?

**Comment by IgorAntun** [comment]
@matrixreal The lag is another issue, I'm going to close this one since it has been solved :)
