### ISSUE TITLE
This is possible?

### ISSUE THREAD

**Issue by mafiakb** [huytd/agar.io-clone#274]
Add W and SPACE?

how agar.io?

**Comment by abalabahaha** [comment]
This is an agar.io clone, not agar.io itself, so it don't really use agar.io's code. Therefore, this clone does not have the code for W and space until someone codes that.

**Comment by IgorAntun** [comment]
Please refer to #47 .

**Comment by abalabahaha** [comment]
@IgorAntun By W and SPACE, I think he meant _*Eject Mass*_ and _*Split*_, which wouldn't go under that issue.

**Comment by IgorAntun** [comment]
@abalabahaha Well, the title of the issue I referenced says "Add keyboard support", so I think it fits just well any keyboard shortcut.

Anyway, if you're talking about the act of splitting and ejecting mass, there are issues for those anyway, so it still is a duplicate.
