### ISSUE TITLE
creating own public serveur ?

### ISSUE THREAD

**Issue by matrixreal** [huytd/agar.io-clone#278]
hi all,
any one can tel me the steps to create our own public serveur (at home for example)
and get agar.io-clone working ... since the demo live is very laggy
thanks

**Comment by abalabahaha** [comment]
@matrixreal Basics at https://github.com/huytd/agar.io-clone/wiki/Setup.

**Comment by matrixreal** [comment]
@abalabahaha 
fail on this step
Install nodejs-legacy  apt-get install nodejs-legacy 
on cmd it say command not found (i already install nodejs)
sad :(

**Comment by Buskcoin** [comment]
Try one of these videos https://www.google.com/#q=installing+node.js+and+npm+on+windows&tbm=vid

**Comment by matrixreal** [comment]
@Buskcoin 
i want to put all the project to deploy agar.io clone to the public serveur

**Comment by Buskcoin** [comment]
Navigate into the directory you cloned the repository into and run npm install

**Comment by matrixreal** [comment]
@Buskcoin 
got this
![nmp install](https://cloud.githubusercontent.com/assets/6823974/8760506/7f66a79c-2d21-11e5-8f96-32c74ca16882.png)

**Comment by matrixreal** [comment]
@Buskcoin 
that make me crazy i try to do it since 3 days without success
i want to put this project (this clone) in my home serveur to be accessible to other (public)
i try again with fresh clone
when i tap npm install now i got these 2 screenshoot
![npm1](https://cloud.githubusercontent.com/assets/6823974/8760527/7998c592-2d22-11e5-90da-ab1e693f7894.png)
![npm2](https://cloud.githubusercontent.com/assets/6823974/8760534/c6a08438-2d22-11e5-8289-21a634018e9a.png)
and after i tap gulp run i got this
![nmp install](https://cloud.githubusercontent.com/assets/6823974/8760538/d949c978-2d22-11e5-9a7f-7d2442c5584f.png)

**Comment by abalabahaha** [comment]
Ok this time you did it right, but something appears to be wrong.

EDIT: Aha! Screenshot the terminal when you type in
```
node -v
```

**Comment by matrixreal** [comment]
got 
v0.12..7

**Comment by Buskcoin** [comment]
Make sure you're running cmd as admin. I'm just guessing here but you may have to install Node v0.8.23 Legacy.

**Comment by matrixreal** [comment]
@Buskcoin 
i will do it now
i just want to contribute to this project 
i have good pc configuration (i5 memory 8gb windows serveur and high speed internet donwload 15 mb / s and upload 500 ko / s)
and i want to put thos project to public serveur 
how can i dot it ? since there no index.html or .php !!!!
i'm confused since 3 days

**Comment by abalabahaha** [comment]
@matrixreal Hosting off home internet is not the best idea, but we can give it a try. Of course there is no index.html or index.php, NodeJS serves that automatically.

Here, try these commands in a new terminal window.
```
cd C:\Users\imatrix\Desktop
git clone https://github.com/huytd/agar.io-clone.git agar
cd agar
npm install -g gulp
npm install
gulp run
```

**Comment by matrixreal** [comment]
@abalabahaha 
as i told you here https://github.com/huytd/agar.io-clone/issues/280

**Comment by matrixreal** [comment]
@abalabahaha 
i will try it on fresh pc
what os you recommand ?

**Comment by abalabahaha** [comment]
Try Ubuntu. After installing it, do these exact steps in terminal (may ask for password and/or restart)
```
sudo apt-get update
sudo apt-get upgrade
cd ~
git clone https://github.com/huytd/agar.io-clone.git agario
cd agario
sudo npm install -g gulp
npm install
gulp run

**Comment by abalabahaha** [comment]
@matrixreal Still having issues?

**Comment by matrixreal** [comment]
@abalabahaha 
i sucess install the server thats okay thanks ...
but it lagg much

**Comment by abalabahaha** [comment]
@matrixreal Lag would probably be pertinent to #188 and #5. #190 has some discussion about lag too. There's not much you can do at this point, gotta wait for someone to take the initiative to resolve those issues. Since this issue is fixed, I'll close it.

**Comment by Logan7432** [comment]
you can fix this by going into config and change networkUpdateFactor from 40 to 120
