### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by reneburghardt** [huytd/agar.io-clone#280]
Hey guys, 

today I just wanted to start my own Open Agar-Server. So installed the clone and everything seems alright beside that I can't push either the start- or the settings-button. Chrome says "Uncaught ReferenceError: require is not defined" on app.js:1 ( var io = require('socket.io-client'); ).

I start the game via "gulp run" or "npm start", not with "node ..." and reinstalled the game twice now.

What am I doing wrong?

Kind regards,
René

**Comment by matrixreal** [comment]
@reneburghardt 
hi
can you tel me what are the steps to install this clone on own serveur ?
because i have good configuration with best internet speed so maybe it will run fast
thanks

**Comment by abalabahaha** [comment]
@reneburghardt Are you sure you installed correctly? Try again with the standard process:
```
git clone https://github.com/huytd/agar.io-clone.git agar.io-clone
cd agar.io-clone
npm install -g gulp
npm install
gulp run
```
Your error makes it seem like you didn't install correctly, as that error shouldn't happen, since we changed that line a week or two ago.

@matrixreal He is also asking for help. We are trying to help you on the issue you opened. I just posted a comment there.

**Comment by matrixreal** [comment]
@abalabahaha 
i just do exactly what you say
but fails on "gulp run" it say that is not a command
i try npm start and got this
![yep](https://cloud.githubusercontent.com/assets/6823974/8766754/38940638-2e44-11e5-93ac-93efebdb6e79.png)

**Comment by abalabahaha** [comment]
@reneburghardt Still having issues?

**Comment by abalabahaha** [comment]
No response for 19 days, closing this issue. Reopen if you still have problems.
