### ISSUE TITLE
create own server on CentOS machine

### ISSUE THREAD

**Issue by yuzmemak** [huytd/agar.io-clone#281]
Hi Guys,

I try to setup own server and I have a cenOS.
I have node.js installed successfull. I can write my own script and run server. But when I run this project it is stuck at the line 4 which is

var express = require('express');

I beleive that my setup is wrong. When I go steps again I see following line is return an error to me

# apt-get install nodejs-legacy
Reading Package Lists... Done
Building Dependency Tree... Done
E: Couldn't find package nodejs-legacy

For installing apt-get; I used following lines
wget http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.2-2.el5.rf.i386.rpm
rpm -i rpmforge-release-0.5.*.rpm
yum install apt
sudo apt-get update

And I could not understand differences between node.js and nodejs-legancany

I hope to hear you guys.

**Comment by abalabahaha** [comment]
Nope. Warning: YOU SHOULD NOT USE APT-GET ON RED HAT SYSTEMS. THAT'S WHAT YUM IS FOR. apt-get is for debian, ubuntu, etc.

You need to build NodeJS from scratch apparently.

**Comment by yuzmemak** [comment]
Hi,

I did npm install in project folder. First error was python revision. I passed this error with using python 2.7. as;

 npm config set python python2.7

Actually centOS python version is 2.4.3 and I am not able to update default python version due to centOS limits. As far as I understand from google search, I set python2.7 as default for npm. Does node.js needs pthon when running server?

I think npm install runs smoothly and creates sub directory called node_modules. Only I have following warnining during install;

npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6

I think this warning is not so important.

What I can not run is;
apt-get install nodejs-legacy

And what I can not understand and find answer is that How important to install nodejs-legancy?

Thanks for all answers.

**Comment by yuzmemak** [comment]
Hi,

When I try to browse with chrome, I see following error at the developer tools pane;

net::ERR_CONNECTION_REFUSED

**Comment by abalabahaha** [comment]
Apparently, one of the modules we use requires python... :/

I suppose you could follow the instructions in this guide: https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

In your case, my belief is that you can skip apt-get install nodejs-legacy

**Comment by abalabahaha** [comment]
@yuzmemak Still having issues?

**Comment by abalabahaha** [comment]
No response for 19 days, closing this issue. Reopen if you still have problems.
