### ISSUE TITLE
Deploy to Heroku not working

### ISSUE THREAD

**Issue by yossi787** [huytd/agar.io-clone#285]
I am just getting an "Application Error" screen..

**Comment by abalabahaha** [comment]
Hmm you're accessing the app on port 3000?

**Comment by abalabahaha** [comment]
Found the current reason: Commit 7fc0d50, which solves #264, causes this.

**Comment by abalabahaha** [comment]
Mehh ignoring my stupid previous comments, Heroku doesn't do a global gulp install, so the command line can't find the command "gulp".

**Comment by IgorAntun** [comment]
@abalabahaha I'm going for option 1. Gonna update it asap.

**Comment by abalabahaha** [comment]
@IgorAntun Pretty much everything.

Without Gulp, the project won't compile
Without Gulp-plugins, Gulp won't run
Without the rest of the libraries, Gulp-plugins won't run

Correct me if I'm wrong someone, but this is what I see from looking at package.json and gulpfile.js

**Comment by yossi787** [comment]
@abalabahaha Thanks you!
