### ISSUE TITLE
Randomly getting kicked

### ISSUE THREAD

**Issue by Jared-Sprague** [huytd/agar.io-clone#296]
I join the game just fine and start zooming around eating food, but after a while I always get kicked with the error message "You were kicked for reason: Last hearbeet received over 5000 ago."  even when I've been active the whole time.  Any idea what's causing this?
Thanks!

**Comment by abalabahaha** [comment]
The only way i could see this happening is if your computer is so slow that your browser hasn't sent anything to the server for 5 seconds. Where is the server hosted?

**Comment by Jared-Sprague** [comment]
Hello! Thanks for the reply! My server is hosted on localhost.  My computer is pretty fast since it's my gaming computer.  Here are my specs:
Fedora 22
Quad core i7 2.67GHz
12 GB RAM
GeForce GTX 500 series

I really doubt that the problem is because my computer is slow since I'm running the server on localhost:3000 so there should be zero network latency.

**Comment by Jared-Sprague** [comment]
Also note I followed the manual new server install steps here:
https://github.com/huytd/agar.io-clone/wiki/Setup

**Comment by abalabahaha** [comment]
try doing the ping command every once in a while in chat (type "-ping" in the chatbox)
