### ISSUE TITLE
How to install this in a webhost?

### ISSUE THREAD

**Issue by matrixreal** [huytd/agar.io-clone#297]
hi all,
i would like to know how to install the server of this project to a webhosting ???
thanks a lot

**Comment by huytd** [comment]
A web hosting is impossible. You need to have the access to the server to install things such as nodejs, npm,... So you need to have a VPS or something similar

**Comment by matrixreal** [comment]
ok i will buy a vps 
so how to install it on vps ?
thanks

**Comment by huytd** [comment]
You can access to the VPS via `ssh`, then follow the instruction in the home page (very simple, just clone the source code to any folder, then run `npm install`) :D

**Comment by matrixreal** [comment]
i'm using windows ? is it same ?

**Comment by huytd** [comment]
yeah, it's the same, you can install NodeJS then open Command Line to run `npm install`

**Comment by abalabahaha** [comment]
Still have any issues @matrixreal ?

**Comment by matrixreal** [comment]
@abalabahaha 
i'm just waiting for the update about sounds and scaling for mobile + joystick etc ...
anyway thanks

**Comment by abalabahaha** [comment]
Those may take a while as nobody appears to have contributed to the project recently, which could be due to summer ending and schools starting.

**Comment by matheuschimelli** [comment]
You can use heroku

**Comment by Logan7432** [comment]
All I did is port forwarded and then typed my up and port into the http, instead of doing localhost:3000 I did my ip:port then I went to no-ip.com and did a web redirect so when someone types in the adress it redirects it to my up and joins my server, simple as pie now my friends can play. My only issues are I can reconnect after splitting

**Comment by abalabahaha** [comment]
@Logan7432 Wrong issue. You already opened #312

**Comment by rade0000** [comment]
I have installed game on my VPS. Can i somehow place a folder client on www.mydomain.com and point him to ip address off my VPS?

**Comment by abalabahaha** [comment]
@rade0000 Not the best place to comment, but whatever.

You first install the project, then go into the config.json and change the port to 80, then run the project. Then you can point the domain to the VPS's IP address and everything will work.

**Comment by rade0000** [comment]
that's not what I asked

**Comment by abalabahaha** [comment]
?

If you really don't want the project to serve the client folder, you could copy the client files to someplace and edit the javascript so it connects to the VPS IP.

**Comment by rade0000** [comment]
That i want but what to change in app.js

**Comment by abalabahaha** [comment]
Not sure as I can't test ATM, but I think it's app.js line 37. Can be changed to:

```socket = io('ip.ad.dr.ess:port', {query:"type=" + type});```
