### ISSUE TITLE
Add a chat

### ISSUE THREAD

**Issue by th3m4ri0** [huytd/agar.io-clone#3]
So we can express our anger when people eat us.

**Comment by huytd** [comment]
Great idea! I will update it ASAP

**Comment by huytd** [comment]
Which kind of chat do you think is better?

A chat box on the corner of screen or a chat bubble on top of a player?

**Comment by huytd** [comment]
Done :dancer:

**Comment by th3m4ri0** [comment]
Chatbox is great ! Good job :+1:

**Comment by IgorAntun** [comment]
I think chat bubbles would be way more interesting, tbh.

**Comment by D3VONT3CH** [comment]
i agree with igor

**Comment by huytd** [comment]
I created a new issue for chat bubbles :D #14

**Comment by arvoim** [comment]
chat bubbles would be fun, but if the map size ever grows to be more than the screen size, most chat bubbles won't be seen by many people unless they are near you. that being said, i think both options of chat should be available (optional to the admin running the game). box, bubbles, or both.
