### ISSUE TITLE
Cell speed

### ISSUE THREAD

**Issue by Netifriik** [huytd/agar.io-clone#30]
Cell should have an invisible radius with a fixed size around it that controls its speed. Currently it's pretty annoying that when you reach the window border your cell slows down dramatically.

**Comment by RemoveIt** [comment]
also I think that cell speed should be independent from distance between cell and cursor or less dependant in bigger part

**Comment by IgorAntun** [comment]
I agree with @RemoveIt I think the speed should be independent from the mouse position.

**Comment by VytorCalixto** [comment]
There's some good normalization over SarenCurrie/agar.io-clone@a7182b9

**Comment by huytd** [comment]
Great fix @VytorCalixto 
Could you make a pull request for this patch, please?

**Comment by IgorAntun** [comment]
Closing it as fixed on #34
