### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by abalabahaha** [huytd/agar.io-clone#300]
@matrixreal did suggest sounds to be added to the game, so that stuff like feeding, eating, being eaten., etc. have sound effects.

[A somewhat pertinent RAR of files](https://www.dropbox.com/s/iyzekwbouofldje/agar-sounds.rar?dl=0)
[VirusTotal scan](https://www.virustotal.com/en/file/87f2256cd564602659da6390b6f4001d5d665aeda02d2cde5b74094356c32d7d/analysis/1441331479/)

**Comment by huytd** [comment]
:+1:

**Comment by matrixreal** [comment]
yes that will be funny and sounds that post are pretty cool
also please autoscaling and add the joystick feed and split image for mobile

**Comment by abalabahaha** [comment]
@matrixreal that is in the original issue you opened. I just split the two main issues you had.

**Comment by matrixreal** [comment]
@abalabahaha 
ok ;)

**Comment by Incognitov** [comment]
I believe I have made a start on this.

**Comment by IgorAntun** [comment]
I'll close this issue as a basic implementation just got merged. We're still looking forward improvements to it, though :)
