### ISSUE TITLE
Merge Split Cells

### ISSUE THREAD

**Issue by abalabahaha** [huytd/agar.io-clone#304]
You currently can't merge after splitting.

Implement merging, preferably after a mass-dependent time frame has passed

**Comment by Logan7432** [comment]
Please please fix this and also I noticed that viruses don't spawn please put like a game server thing to edit player slots, food, virus amount, ECT

**Comment by abalabahaha** [comment]
@Logan7432 This is by no means a finished product. Wait patiently :P

**Comment by Logan7432** [comment]
someone please fix ill do anything like anything

**Comment by underGhost** [comment]
Going through your guys's tickets and it looks like this one has already been merged.
