### ISSUE TITLE
Steps to debug server?

### ISSUE THREAD

**Issue by Jared-Sprague** [huytd/agar.io-clone#325]
Hello!
I'm pretty new to node, so forgive the noob question.  How would I go about setting a breakpoint in the server.js and inspecting it in a debuger?  What process do you use?

Thanks!

**Comment by abalabahaha** [comment]
@Jared-Sprague Does https://nodejs.org/api/debugger.html help?

**Comment by Jared-Sprague** [comment]
Thanks that helped a lot!
