### ISSUE TITLE
Merging reverts mass gained

### ISSUE THREAD

**Issue by abalabahaha** [huytd/agar.io-clone#326]
According to @Logan7432, when you split, eat stuff, and merge, the mass gained while split is lost.

Also, merging is claimed to have slown people down.

**Comment by Logan7432** [comment]
Correct

**Comment by Logan7432** [comment]
my idea of this is to make it so after about 30 seconds when your body parts start to go back together make it so you eat your own cells just like you eat people and you get bigger

**Comment by abalabahaha** [comment]
Should be fixed now.

**Comment by Logan7432** [comment]
Thank you very much for fixing this bug! This project is almost done all it needs is viruses and a score, Keep up good work!
