### ISSUE TITLE
Why isn't sockets an array?

### ISSUE THREAD

**Issue by Jared-Sprague** [huytd/agar.io-clone#331]
Hello quick question about the code.  I'm still pretty new to JavaScript so this is a noob question. I noticed that the server holds most of it's state in arrays, but for some reason sockets is defined as an object?

```JavaScript
var users = [];
var massFood = [];
var food = [];
var sockets = {};
```

Why not `var sockets = []`  just curious if there was a reason to make this an object instead of an array?  Thanks!

**Comment by abalabahaha** [comment]
IIRC as a hash, we can get a socket by doing sockets[socketID] instead of looping through an entire array to find the socket we want

**Comment by Jared-Sprague** [comment]
Thanks!

**Comment by abalabahaha** [comment]
@Jared-Sprague [You could also ask questions in the Gitter.IM chat, instead of opening an issue for question you have.](https://gitter.im/huytd/agar.io-clone)
