### ISSUE TITLE
dots

### ISSUE THREAD

**Issue by Logan7432** [huytd/agar.io-clone#336]
is there a way i can change the dots from looking like demented circles to round circles?

**Comment by francisco-maciel** [comment]
Yes, just create a pull request with your solution

**Comment by huytd** [comment]
Actually, in the beginning, it was round circles :laughing:

**Comment by Logan7432** [comment]
haha... i didnt realize at first but i went and played the main agario and saw round circles then im like wait a second and looked at agario clone and there like demented and im like what is going on here!

**Comment by Logan7432** [comment]
and if i wanted to change these how would i? or can someone help me out and do it that is more experienced then me.

**Comment by abalabahaha** [comment]
Some want to travel through old code and make a toggle?

**Comment by Logan7432** [comment]
? I'm sorry I didn't get that?

**Comment by abalabahaha** [comment]
@Logan7432 not directed toward you. Just a general question.

**Comment by CarlBarr** [comment]
agar.io-clone/src/server/server.js  line 53
```
sides: 5 + Math.round(Math.random() * 3)
```
if have more sides it is more like a circle

**Comment by abalabahaha** [comment]
Added rounded food toggle, and a configurable chat command `-roundfood` (triangle food is possible).
