### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Logan7432** [huytd/agar.io-clone#337]
I changed the line "sides: 5 + Math.round(Math.random() * 3)" to make the dots round and only 90% of the dots are round now there are a few dots that still only have like 4 to 6 sides on them am i missing something?

**Comment by jturbo26** [comment]
What did you change it to?

**Comment by abalabahaha** [comment]
I believe that's what he changed it to.

**Comment by abrad1212** [comment]
I like turtles

**Comment by abalabahaha** [comment]
Should be fixed.
