### ISSUE TITLE
not works

### ISSUE THREAD

**Issue by atilaro** [huytd/agar.io-clone#338]
hey, i follow those steps, and the steps works:
git clone https://github.com/huytd/agar.io-clone.git agar.io-clone
cd agar.io-clone
npm install -g gulp
npm install
gulp run

but still not working 

http://powerdigital.com.br/jogo/src/client/index.html

**Comment by atilaro** [comment]
has any action to see with im running the gulp right?

**Comment by abalabahaha** [comment]
You need to keep the program running, then go to http://your-server-address:3000/

**Comment by huytd** [comment]
It's about 10 days with no feedback, please allow me to close the issue now. 
Feel free to reopen whenever you want.
