### ISSUE TITLE
Changing Title of Window

### ISSUE THREAD

**Issue by SphinxTwo** [huytd/agar.io-clone#342]
This is more of a question than an issue, but where would I be able to change the "Agar.IO Clone" title in the browser tab?

**Comment by huytd** [comment]
You can change it easiliy here https://github.com/huytd/agar.io-clone/blob/2a03b5039de738c1212c1bfbc3cf6ade8fa1129f/src/client/index.html#L5

**Comment by SphinxTwo** [comment]
It works, thank you :D
