### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by 3642066** [huytd/agar.io-clone#345]
I'm using Heroku and Chrome, after splitting and merge, the mass is the starting mass .
I can help you to implement Facebook, including Facebook Scores on the project .

**Comment by abalabahaha** [comment]
Someone reported it before you in #326 :/ 

Great! If you want to help, you can always fork, make changes, and submit a pull request!

**Comment by 3642066** [comment]
I'm a kinda confused when exploring github, sorry .. that was the first time i did this .. i dont know how to use Github, im very very noob on it .. but i will do my best .
I just found another fork that implements virus, and i could update the clone i updated to Heroku .. it worked :) and another bug when one player eats another, fixed too ... This project is awesome, you are doing a great work .. I'm really trying to help .. I can help you implement Facebook SDK .. 
I can help you testing too .. you just need to tell me what to do :)
Can I start implementing basic Facebook SDK ?
I should create a fork, then i implement Facebook SDK, test it, and then i submit a pull request ?
Is this how it work ?
What if I make changes, and after pull request you update main code ?
How can i get your updates without loosing my changes at my fork ?
I changed it locally only :P and updated it on Heroku ;) 
Its on : iogar.herokuapp.com .. i included it on your Wiki (Demos) .
But there is a problem with that small and green image .
Its pointing to my server, but with the image of the other, i dont know how you did that .

**Comment by IgorAntun** [comment]
>This project is awesome, you are doing a great work

Thank you!

>I should create a fork, then i implement Facebook SDK, test it, and then i submit a pull request ?
Is this how it work ?

Yes, that's pretty much it!

>What if I make changes, and after pull request you update main code ?

You should then send us another pull request, with the updated code.

>How can i get your updates without loosing my changes at my fork ?

Just use `git pull` to pull the code from our repository, it should be easy enough.

>But there is a problem with that small and green image .
Its pointing to my server, but with the image of the other, i dont know how you did that .

No problem, I fixed it :)
