### ISSUE TITLE
Food Spawn Issue

### ISSUE THREAD

**Issue by MastaCoder** [huytd/agar.io-clone#348]
Hey Guys. I just read the readme.md file on root, I read this part of the readme:

Everytime a player joins the game, 3 food particles will spawn
Everytime a food particle is eaten by a player, 1 new food particle will respawn

Wouldn't the 3 food spawning cause an issue if too many players spawn? Try to make it so that the 3 food particles will get removed and not spawn back if a user has left the game.

**Comment by abalabahaha** [comment]
IIRC that is outdated information. Have you actually tried this?

Also, the way you suggested will not work because there eventually won't be any food particles left.

**Comment by MastaCoder** [comment]
Alright, I'll try it.
