### ISSUE TITLE
Button play cannot be clicked

### ISSUE THREAD

**Issue by DevilLordSR-MCPE** [huytd/agar.io-clone#351]
agar.mcpei.net/src/client/index.html
my play button cant be clicked

**Comment by abalabahaha** [comment]
It cannot be clicked because it cannot establish a connection to the server. If you run the project with node, it will automatically serve the files on the configured port, without need for a separate web server to host the files.

**Comment by DevilLordSR-MCPE** [comment]
i use cpanel
how to install node in cpanel

**Comment by abalabahaha** [comment]
Oh... You need a VPS for hosting... You can't use a web host.

**Comment by DevilLordSR-MCPE** [comment]
.......
