### ISSUE TITLE
Should create Players and Player object

### ISSUE THREAD

**Issue by bjarneo** [huytd/agar.io-clone#36]
Should create Players and Player object.

Players should be initialized once to hold all players object. It should also have all the methods related to findPlayer, getPlayersList etc.

The Player object should have the x, y etc. And it should probably inherit the playerConfig. This object should be initialized in socket.on("welcome", function(us

Perhaps it also should be packed in webpack, so the code could be shared on the client and server side?

Thoughts?

**Comment by bjarneo** [comment]
*between client and server

**Comment by RemoveIt** [comment]
Also we can take into account entity-component-system pattern. It's commonly used pattern in gamedev but I'm not sure if it won't be overkill

little tutorial/demonstration
http://vasir.net/blog/game-development/how-to-build-entity-component-system-in-javascript

**Comment by RemoveIt** [comment]
I think that when we start playing with oop it would be nicer if we would write classes with es6 (babel or typescript or whichever compiler which can compile down to es5). OOP code in es6 looks much clearer than es5

**Comment by bjarneo** [comment]
I like this ECS system. I'll take a closer look at it.

**Comment by huytd** [comment]
I agree. We should write classes with ES6 :D

**Comment by RemoveIt** [comment]
But for es6 we need compiler which is impying build system. Which one you prefere? I'm suggesting gulp

**Comment by huytd** [comment]
Gulp is much familiar to me :)

**Comment by huytd** [comment]
Yes, Gulp is much easier to use. I think.

**Comment by RemoveIt** [comment]
@huytd i can setup gulp with babel also I'll create issue for this

**Comment by huytd** [comment]
:+1:
