### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Agarian** [huytd/agar.io-clone#369]

**Comment by proxiemind** [comment]
Hi @Agarian 

Funny think, I tried google (of course not only this phrase) "Project independent best practices of creating issues", but I can't find anything useful, "independent" guidelines - I think I will spent some time to make it.

Ok, as for this issue briefly:

1. Think about what "other side" would like to know about your problem:
 * Try to reproduce step by step your problem and write it down, so someone can create same situation and provide you with answer/solution
 * If you have any error in console, paste it
 * Consider providing more: a screenshot, description of problem found example in UI "Cells are glitchy, they don't behave as in agar.io, I can't do tricks" or something like that
2. Please redo your description and tittle, "doesnt work" and no desc... it's a little bit silly :smile: 

I assume, but I might be wrong, that almost all reported issues... are not issues - pls ask question first here next time: https://gitter.im/huytd/agar.io-clone?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

And last think: I have a feeling that you have problems with setup, am I right? :smile: 
So please start redo from point 1 above, and we will see what we can do.

Cheers

**Comment by Agarian** [comment]
the unfortunate thing is this no longer has purpose with minions. miniclip patched them
