### ISSUE TITLE
You're always under the virus

### ISSUE THREAD

**Issue by Incognitov** [huytd/agar.io-clone#371]
Hey,

Recently a member of the community added a continuation of the virus implementation, and that's just great news! It's been working well. Unfortunately, I've encountered a minor bug:

![](http://imgur.com/FJzplce.png)

As you can see, regardless of the mass I have I'm always under the virus at all times. Don't worry about the styling, I've just customised it to fit my theme.

**Comment by underGhost** [comment]
It's the order of the rendering. I can place the user over the virus and push it up with my color update.

**Comment by Incognitov** [comment]
Sure. Would a minimal mass be possible to set? So if it's under 100 it will render underneath the virus, and if it's over 100 it will render above (for example).

**Comment by underGhost** [comment]
Canvas isn't aware of any z-index so this is all based off the initial render. We could re-render viruses you touch based off your size, but with the cpu load issues already this may be better to hold off until those are addressed.

**Comment by Incognitov** [comment]
Ah yes, I remember this when having a look at the code a while ago. Yes I agree, anything which could prove intensive to the CPU should be avoided for now. We could always postpone this for later.

**Comment by 3642066** [comment]
Wow. Thank you. That was exactly what i have been reported on last weeks .
You are doing an awesome work .
Congratulations .
