### ISSUE TITLE
Just the client?

### ISSUE THREAD

**Issue by jollesnaas** [huytd/agar.io-clone#379]
Hey, I realy realy realy like all the work that has token this project, but: can you make it compatible with cigar or ogar? And a multi server selection menu should be realy epic!
Thanks!

**Comment by abalabahaha** [comment]
I think compatibility with those is outside the scope of this project

**Comment by IgorAntun** [comment]
Yes, I don't think we're looking for compatibility with alternative servers/clients right now.
