### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by KryptonicDev** [huytd/agar.io-clone#383]
So I read the TODO list and it say we need to add skins, so I came up with this:
`   if (playerName = "doge") {
player.style.backgroundImage = "url('skins/doge.png')";
} `
Don't know if it works, I am very new at this stuff, just thought of it and wanted some feedback from the community. And ofcourse we would need to create a folder for the skin images. @huytd

**Comment by huytd** [comment]
Nice try :D it's almost solved the problem. One issue is we're using canvas to draw characters so instead of setting backgroundImage. We should draw it, with a mask to make sure image will not overflow the circle shape. And yes, since we implement this, we need a folder to store skins image.

**Comment by KryptonicDev** [comment]
Ok cool :smiley:

**Comment by Dve4Ever** [comment]
is this being worked on still?
