### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by huytd** [huytd/agar.io-clone#39]
It's time to talk about unit testing. 
I used Jasmine for many of my previous project so I choose Jasmine.
If you got any better idea (mocha/chai or something, idk), please suggest.

**Comment by huytd** [comment]
This is a good article about how to use Jasmien for testing NodeJS application
http://blog.codeship.com/jasmine-node-js-application-testing-tutorial/

**Comment by jniles** [comment]
I am most familiar with [Mocha](http://mochajs.org/) and [Chai](http://chaijs.com/) for testing NodeJS.  Testing WebSockets seems rather difficult.  I didn't find any clear tutorials with Jasmine, but I did find [this](http://liamkaufman.com/blog/2012/01/28/testing-socketio-with-mocha-should-and-socketio-client/) for Mocha.  Would it be acceptable to test the server using Mocha and Chai?

**Comment by MadaraUchiha** [comment]
:+1: for Mocha/Chai.

**Comment by jniles** [comment]
Sounds good.  I'll take a look at implementing some test cases.
