### ISSUE TITLE
Configing the config.json Not working

### ISSUE THREAD

**Issue by Alicoolman** [huytd/agar.io-clone#396]
I am running Ubuntu and made my own agario server clone, when I try configuring the config.json file and start the server the server dose not change any settings.

**Comment by Alicoolman** [comment]
Found out how to do it
run terminal as root by using `sudo -i` then your root password.
Then go to agar.io-clone file by typing `cd agar.io-clone`
then edit the config.json file in terminal by using the command `sudo pico config.json`
then start server by typeing `gulp run`

**Comment by abalabahaha** [comment]
Typically, just editing the config.json, saving, and typing `gulp run` again works
