### ISSUE TITLE
Change language?

### ISSUE THREAD

**Issue by nizarnizario** [huytd/agar.io-clone#400]
Hello,
First of all thanks for this great project , i really look forward to help developing new features with you ,
but for the moment , i was wondering how/if i can change language from English to French or Spanish?

Thank you.

**Comment by tutosfaciles48** [comment]
is a great idea

**Comment by IgorAntun** [comment]
Please check out #149

**Comment by IgorAntun** [comment]
We appreciate any help you could give :)
