### ISSUE TITLE
Min Mass For Mass Loss

### ISSUE THREAD

**Issue by PHREADDMINER** [huytd/agar.io-clone#403]
Can we find a way to implement a minimum mass required to start the constant mass loss?

**Comment by wb9688** [comment]
If you're using the `es6-refactor` branch you could change `if (c.mass * (1 - (Config.massLossRate / 1000)) > Config.defaultPlayerMass) {` to `if (c.mass * (1 - (Config.massLossRate / 1000)) > Config.defaultPlayerMass && u.massTotal > Config.minMassLoss) {` in `server/index.js` and add `"minMassLoss": 50,` under `"massLossRate": 1,` in `config.json`.
