### ISSUE TITLE
i Ran npm start on windows 10

### ISSUE THREAD

**Issue by xXhydraXx** [huytd/agar.io-clone#404]
> agar-clone@1.0.0 start C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone
> gulp run

module.js:327
    throw err;
    ^

Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone\node_modules\gulp-util\index.js:2:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! agar-clone@1.0.0 start: `gulp run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the agar-clone@1.0.0 start script 'gulp run'.
npm ERR! This is most likely a problem with the agar-clone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs agar-clone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls agar-clone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone\node_modules\npm-debug.log

**Comment by abalabahaha** [comment]
Are you sure your `npm install` ran properly? It appears you are missing a dependency

**Comment by xXhydraXx** [comment]
@abalabahaha npm WARN unmet dependency C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone\node_modules\socket.io-client\node_modules\engine.io-client requires component-emitter@'1.1.2' but will load
npm WARN unmet dependency C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone\node_modules\socket.io-client\node_modules\component-emitter,
npm WARN unmet dependency which is version 1.2.0
npm WARN unmet dependency C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone\node_modules\socket.io-client\node_modules\socket.io-parser requires component-emitter@'1.1.2' but will load
npm WARN unmet dependency C:\Users\Classic Toxin\Documents\GitHub\agar.io-clone\node_modules\socket.io-client\node_modules\component-emitter,
npm WARN unmet dependency which is version 1.2.0
that is my log when installing

**Comment by xXhydraXx** [comment]
Fixed
