### ISSUE TITLE
SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by PeterDaveHello** [huytd/agar.io-clone#429]
Built from master commit https://github.com/huytd/agar.io-clone/commit/a971f38ae3a1ae0508c6967058291161fac8cc5b, error was shown in browser console and located in app.js:8275:1

**Comment by abalabahaha** [comment]
Should be fixed with c710741

**Comment by PeterDaveHello** [comment]
:+1:
