### ISSUE TITLE
Application Error on Heroku

### ISSUE THREAD

**Issue by ili-codes** [huytd/agar.io-clone#436]

**Comment by PortPixel** [comment]
Same problem here

**Comment by ili-codes** [comment]
I did try on [Nitrous](http://nitrous.io) and it worked under NodeJS Settings, then a `npm install` then `npm start`. However, Nitrous has long URLs, which can be fixed by shortening the URL (i recommend bit.do) OR getting a domain (dot.tk).

**Comment by huytd** [comment]
Sorry, accidentally closed :sweat_smile: I found the problem, will fix it ASAP

**Comment by huytd** [comment]
I fixed in #441. Heroku now able to work fine.

Could you check it again please? @ili-codes @PortPixel
