### ISSUE TITLE
Player doesn't stop moving when window is focused out

### ISSUE THREAD

**Issue by ajan1** [huytd/agar.io-clone#44]

**Comment by IgorAntun** [comment]
Could you please elaborate on how to reproduce this bug?

**Comment by ajan1** [comment]
1. Open game in window
2. Move mouse over window
3. Click something else than game window
4. Go back to game
5. Ball continue moving to last direction

Tested with Windows 8.1 and Chrome 43

**Comment by IgorAntun** [comment]
Oh I see, that's because we aren't listening for the `onblur` event. Thanks for pointing that out! :)

**Comment by jniles** [comment]
Has this been addressed?  If not, I'll put in a patch for it.

**Comment by ZeHaxor** [comment]
No it hasn't, should be easy to fix

**Comment by IgorAntun** [comment]
@jniles go for it ;)
