### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by ajan1** [huytd/agar.io-clone#46]
Any of demos not work.

**Comment by IgorAntun** [comment]
@huytd Could you please check our demos at Heroku and your site? I'll remove the OpenShift one as requested by the guy who made it.

**Comment by Ariamiro** [comment]
I am hosting a new demo, please don't remove my c9 demo

**Comment by Ariamiro** [comment]
new demo url:
https://agar-io-clone-d3vont3ch.c9.io/
the new demo is permanent, i guarantee.

**Comment by IgorAntun** [comment]
@Ariamiro Ok. Is that demo up to date, by the way?

**Comment by Ariamiro** [comment]
I think so, I cloned the repository, but the game has not colored food and other things he had before

**Comment by IgorAntun** [comment]
Try `git pull`'ing it then.

**Comment by Ariamiro** [comment]
already-up-to-date
are you sure that no commit removed a game feature?

**Comment by IgorAntun** [comment]
Are you sure you are pulling from this repository, instead of your fork? Try `git pull https://github.com/huytd/agar.io-clone.git master` instead.

**Comment by Ariamiro** [comment]
no, i cloned the right repository, but i can see that the features are on other repository
https://github.com/huytd/agar.io-clone/compare/master...PETComputacaoUFPR:master
colored food, fire a food, new command system, etc, are here
can't you merge these repo's?

**Comment by IgorAntun** [comment]
@Ariamiro There are some merge conflicts they need to solve before sending the pull request. @VytorCalixto could you please take a look at that?

**Comment by VytorCalixto** [comment]
Currently we have three other features on [PETComputacaoUFPR/agar.io-clone](https://github.com/PETComputacaoUFPR/agar.io-clone) that are not here:

1. Random colored food and players
2. Respawn
3. Fire food

There are still some bugs on the last one that appeared on a recent merge with huytd/master. We are trying to fix them and will make a pull request then.

**Comment by IgorAntun** [comment]
Sounds great @VytorCalixto, looking forward for that PR, but I digress.
Back to that issue topic, I'm closing it since it's been somehow fixed and we're going to look into those demos. Thanks for reporting it :)
