### ISSUE TITLE
Remove virus after split [Idea]

### ISSUE THREAD

**Issue by Awersione** [huytd/agar.io-clone#464]
When splite  by the virus of the current version, the virus can not be deleted.

example code:

`server.js`

`find: function deleteFood(f)`
`add below function`

`function deleteVirus(f){
        virus[f] = {};
        virus.splice(f, 1);
    }`

find : 
`if(virusCollision > 0 && currentCell.mass > virus[virusCollision].mass) {`
          `sockets[currentPlayer.id].emit('virusSplit', z);`
        `}`

replace with :
`if(virusCollision > 0 && currentCell.mass > virus[virusCollision].mass) {`
          `sockets[currentPlayer.id].emit('virusSplit', z);`
         `virusCollision.forEach(deleteVirus);`
        `}`

**Comment by vikramdurai** [comment]
I created a [pull request] (https://github.com/huytd/agar.io-clone/pull/493)
