### ISSUE TITLE
Open Chat Box

### ISSUE THREAD

**Issue by jjwallace** [huytd/agar.io-clone#468]
I know this is probably in documentation somewhere but i am dumb.  How do we actually open the new chat box feature?

**Comment by mowshon** [comment]
Enter.

https://github.com/huytd/agar.io-clone/blob/bcf476180f92aae83277b7fd4d919130bea94630/src/client/js/global.js#L4-L5

**Comment by Max1Truc** [comment]
It's fixed, jjwallace, so I think you can close this issue.
