### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by IgorAntun** [huytd/agar.io-clone#47]
Support A/W/S/D and/or UP/DOWN/LEFT/RIGHT arrow keys.

**Comment by bigfoot90** [comment]
Please +1

**Comment by francisco-maciel** [comment]
How should this  interaciton work?

 Would you use both the mouse and the arrow keys? This way the currently pressed arrow key would apply a force, but still having the same target direction? 

Or should this work by replacing the movement method entirely?

**Comment by IgorAntun** [comment]
That's open for discussion :)
I think something like: when you press a key, it ignores the mouse position (disables the mouse interaction while pressed) and applies the force in the direction of the key you pressed.

What do you think?

**Comment by abalabahaha** [comment]
I feel like we should still have mouse targeting, but if keys are pressed, override the mouse target with the keys. The eight basic directions possible with 4 keys should suffice

**Comment by IgorAntun** [comment]
@abalabahaha Exactly, that's what I meant in case I didn't word it well enough, I'm bad at explaining ideas :P

**Comment by abalabahaha** [comment]
Ahh whoops, sorry. :+1: then.

**Comment by francisco-maciel** [comment]
Got it, I'll have a go at it then

**Comment by IgorAntun** [comment]
Done in #322 thanks to @francisco-maciel :tada:
