### ISSUE TITLE
Server crashing on gulp run

### ISSUE THREAD

**Issue by dmhzmxn** [huytd/agar.io-clone#477]
Ummmmmmm whhhhhat?
I'm just trying to run it and it crashes and the console window closes.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle agar-clone@1.0.0~prestart: agar-clone@1.0.0
6 silly lifecycle agar-clone@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle agar-clone@1.0.0~start: agar-clone@1.0.0
8 verbose lifecycle agar-clone@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle agar-clone@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\duharris\Desktop\agar.io-clone-master\node_modules\.bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\1E\NomadBranch\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Users\duharris\AppData\Roaming\npm
10 verbose lifecycle agar-clone@1.0.0~start: CWD: C:\Users\duharris\Desktop\agar.io-clone-master
11 silly lifecycle agar-clone@1.0.0~start: Args: [ '/d /s /c', 'gulp run' ]
12 silly lifecycle agar-clone@1.0.0~start: Returned: code: 7  signal: null
13 info lifecycle agar-clone@1.0.0~start: Failed to exec start script
14 verbose stack Error: agar-clone@1.0.0 start: `gulp run`
14 verbose stack Exit status 7
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid agar-clone@1.0.0
16 verbose cwd C:\Users\duharris\Desktop\agar.io-clone-master
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error agar-clone@1.0.0 start: `gulp run`
22 error Exit status 7
23 error Failed at the agar-clone@1.0.0 start script 'gulp run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the agar-clone package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs agar-clone
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls agar-clone
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Nikitaw99** [comment]
Try updating `npm` and `nodejs`, or download them if they are not installed. (`npm` is included with `nodejs`)

If it still doesn't work, try downloading again, since the files might have been corrupted.

**Comment by dmhzmxn** [comment]
That resolved it, thanks!
