### ISSUE TITLE
ECONNRESET error when MySQL is not running

### ISSUE THREAD

**Issue by TheCodeCrafter** [huytd/agar.io-clone#488]
I keep getting this error. I don't know how to fix this!

{ [Error: connect ECONNREFUSED 127.0.0.1:3306]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }

Any idea what this means?

**Comment by abalabahaha** [comment]
It seems that the recently merged database integration PR (#471) isn't accounting for not having a database...

@huytd did you check this before merging?

**Comment by TheCodeCrafter** [comment]
For the meantime: Could someone explain how to get a database for the server (Node.js)

**Comment by TheCodeCrafter** [comment]
Abalabahaha, I can't find an agar.io client to use! Where is one that I can use?

**Comment by flaminggenius** [comment]
Just submitted a pull request fixing this
