### ISSUE TITLE
Bots?

### ISSUE THREAD

**Issue by FeaturedSpace** [huytd/agar.io-clone#491]
Could someone show me how I could implement bots onto this server? An example of this is on the Ogar server: https://github.com/OgarProject/Ogar/

**Comment by ozjd** [comment]
It's open source. If you must, you should read the code.

**Comment by TheCodeCrafter** [comment]
I know, however, it has a very different structure than this project....

**Comment by Faris90** [comment]
use https://github.com/Faris90/Ogar3 it can be deployed to heroku

**Comment by FeaturedSpace** [comment]
Thanks :D
