### ISSUE TITLE
Better client

### ISSUE THREAD

**Issue by vikramdurai** [huytd/agar.io-clone#499]
I think this project needs a better client library than simple HTML5 Canvas. Using a drawing library like [p5.js](https://p5js.org) or [paper.js](https://paperjs.org) would not only better the drawing quality, but also reduce a huge amount of code.

**Comment by huytd** [comment]
Agree. paper.js has this demo http://paperjs.org/examples/meta-balls/ which will be extremely helpful if we want to have the fluid-like effect in original agar.

**Comment by vikramdurai** [comment]
or also the [Candy Crush](https://paperjs.org/examples/candy-crush) example, which would be helpful. All we'll have to do is change the collision code. Instead of bouncing in the opposite direction, we could change the collision to make a mass check.

**Comment by vikramdurai** [comment]
Any progress on this @huytd
