### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by themuddfamily2** [huytd/agar.io-clone#59]
I get connection refused whenever I run this, I have reinstalled the server 3-4 times now and I am still getting this error, thanks. there are no errors appearing at all it just says "listening on port :3000" here is the server I am running it on http://23.94.96.14:3000/

**Comment by huytd** [comment]
Hmm, this is strange. Could you check your server if port `3000` is allowed? And how did you start the game on this server?

**Comment by themuddfamily2** [comment]
I followed the tutorial exactly on the https://github.com/huytd/agar.io-clone/blob/master/README.md
And yes port 3000 is allowed as I had IgorAntuns copy running on the same server.

**Comment by huytd** [comment]
Did you access to the server via SSH?

**Comment by themuddfamily2** [comment]
Yes

**Comment by themuddfamily2** [comment]
Oh wow, I just tried again and its working now, sorry for this.

**Comment by huytd** [comment]
Great :D Could you share us the reason why the game isn't work few days ago?

**Comment by huytd** [comment]
Great :D Could you share us the reason why the game didn't work few days ago?

**Comment by themuddfamily2** [comment]
Im not even sure, I just reinstalled it and it suddenly worked.
