### ISSUE TITLE
Issue assigment

### ISSUE THREAD

**Issue by RemoveIt** [huytd/agar.io-clone#67]
Please assign yourself to whatever issue you want solve. I want to contribute but I dont know on which one peaple are currently working.

**Comment by IgorAntun** [comment]
I think we could just have people comment something like "Working on this" on the issue they're working on, so we could assign it to them and other people would know which issues aren't being worked on yet.

**Comment by RemoveIt** [comment]
Another option is to use  #<issue_index> in commits

**Comment by huytd** [comment]
Yes we should have the issue number in commits. And you can assign any task you want if you can do it by yourself. If not, you can put a comment as Igor said.
