### ISSUE TITLE
Menu Feature?

### ISSUE THREAD

**Issue by Ariamiro** [huytd/agar.io-clone#69]
a menu that you can choose your name can be very cool.

**Comment by RemoveIt** [comment]
I can do this

**Comment by RemoveIt** [comment]
![agar-menu](https://cloud.githubusercontent.com/assets/8374421/7899279/516f86d0-071d-11e5-8aa4-0d673ddd6947.PNG)

rate my menu :innocent:

**Comment by Ariamiro** [comment]
Pull Request from your repo?

**Comment by RemoveIt** [comment]
If you think that it is ready then you can pull

**Comment by Ariamiro** [comment]
Closed, pullrequest waiting approvation.
