### ISSUE TITLE
Player should move slower when cursor is near own cell

### ISSUE THREAD

**Issue by RemoveIt** [huytd/agar.io-clone#70]
I'm taking this if approved

**Comment by IgorAntun** [comment]
It worked that way before, but it turned out to be really hard to controll your cell if you're near the screen border, I think it'd be good only if it was a small difference.

**Comment by RemoveIt** [comment]
> near the screen border
but now cell is always in center of screen

**Comment by IgorAntun** [comment]
That's true, good point. Fine by me, you can start working on it if you want ;)
Unless someone has a counter argument, ofc.

**Comment by IgorAntun** [comment]
Closed as of #71
