### ISSUE TITLE
What tool did you use to generate images in the document?

### ISSUE THREAD

**Issue by bsapwindows** [huytd/agar.io-clone#74]

**Comment by totty90** [comment]
+1 I really enjoyed them. Example: https://camo.githubusercontent.com/8f5cccdd016acdae5d59a1dc2ccb799eb70bbe59/687474703a2f2f692e696d6775722e636f6d2f713057574978742e706e67

**Comment by huytd** [comment]
Thank you so much. I'm glad that you like it. 
I draw these images with Adobe Illustrator. But Sketch 3 is also possible to make images like this.

**Comment by IgorAntun** [comment]
Closing it since it has been answered :)
If you have any following questions related to this feel free to reopen it.
