### ISSUE TITLE
Menu improvement

### ISSUE THREAD

**Issue by huytd** [huytd/agar.io-clone#77]
@RemoveIt has done a great work at #75 
So now we can do some CSS to give the menu a better look. I suggest this design:
![screen shot 2015-05-31 at 10 22 12 pm](https://cloud.githubusercontent.com/assets/613943/7902461/e19afd44-07e4-11e5-80b0-dc6829abb6a3.png)

**Comment by Ariamiro** [comment]
wow, already done?

**Comment by RemoveIt** [comment]
How server location would be determined?

**Comment by Ariamiro** [comment]
we can use a css framework
my list:
http://purecss.io/
http://imperavi.com/kube/
http://www.gumbyframework.com/
http://foundation.zurb.com/
http://getskeleton.com/
http://materializecss.com/
http://tuktuk.tapquo.com/
http://semantic-ui.com/
http://concisecss.com/
http://getuikit.com/
http://material-ui.com/#/
https://www.muicss.com/
and the framework used by agar.io:
http://getbootstrap.com/

**Comment by huytd** [comment]
@RemoveIt we can put a config or a variable in the code to tell the server location.

**Comment by huytd** [comment]
@Ariamiro Bootstrap is much better, but I'm afraid that it will increase the client size. If we use the simple design, we can write CSS manually. It much faster and keep the game size small. What do you think?

**Comment by RemoveIt** [comment]
If this menu is only thing that needs styling we can stay without css framework

**Comment by Ariamiro** [comment]
@huytd 
like this: 
var ServerLocation = US
var US = United States

we can use a style from a framework.

**Comment by huytd** [comment]
Currently, most of our code is in HTML5 Canvas, only this menu and the Chatbox are HTML elements for now. 

@Ariamiro yes, just something like:
```
var serverLocation = "United States";
// or
var serverLocation = "US West";
```

**Comment by Ariamiro** [comment]
you can see my css in: https://agar-io-clone-d3vont3ch.c9.io/
i am editing the css

**Comment by huytd** [comment]
Cool.
But you can give the `#startMenu` some padding. 
Then the textbox and button `width: 100%` and `box-sizing: border-box`
Don't need the margin :)

**Comment by Ariamiro** [comment]
ok.

**Comment by empty206** [comment]
My panel currently looks like this: https://agar-poznan.c9.io :)

**Comment by Ariamiro** [comment]
good job.

**Comment by huytd** [comment]
Great :D we should put some instruction in the panel as @empty206 did

**Comment by empty206** [comment]
My game will be earmarked in Polish, so I took Polish descriptions.

English:
Available commands:
'-help'
'-dark'
'-ping'

2015 | All rights reserved.

**Comment by Ariamiro** [comment]
i am going to restart my menu, you can use the empty206 menu if you want.

**Comment by IgorAntun** [comment]
What about being able to "watch" the game behind the menu, with some transparency? Just so it's not that dark gray background?

**Comment by huytd** [comment]
With the current code, the game is not connected to server when the menu displayed yet :D 
I pushed a commit. The menu now look like this. 
If anyone want to improve it more, feel free to reopen this issue.

![screen shot 2015-06-01 at 10 08 03 pm](https://cloud.githubusercontent.com/assets/613943/7915907/c1e0f15e-08aa-11e5-970d-7ffc993758bb.png)
