### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by jniles** [huytd/agar.io-clone#78]
Adding a license (MIT seems like it would fit the project best) lets a contributor know how their code will be used in the future.  Could you add one?

**Comment by huytd** [comment]
OK, I will take a look at the licenses and see which one is better :D MIT seem good

**Comment by IgorAntun** [comment]
I recommend MIT as well ;)

**Comment by Calinou** [comment]
:+1: for MIT, or Apache 2.

**Comment by alketii** [comment]
GPL v3 could be fine too, but +1 for a free license.

**Comment by bojidar-bg** [comment]
:+1: for MIT or WTFPL :smile:

**Comment by fry-** [comment]
:100: :+1: for free software license! :smile:

**Comment by huytd** [comment]
Actually, for me, this product is 100% free and open for everyone, you can use it in any purpose.
I don't know if is there any license match this? And how about the other contributors think?

**Comment by Calinou** [comment]
You should add a formal license to your project, in order to make it sure that people are legally allowed to use it; see <http://choosealicense.com/> for more information.

**Comment by Ariamiro** [comment]
if you want people using the game for any purpose choose Public Domain, if you want a good & simple license choose MIT, i don't recommend you to keep without a license.

**Comment by huytd** [comment]
OK. Just go with MIT :D

**Comment by huytd** [comment]
I added license :)

**Comment by Ariamiro** [comment]
(y) good choice
