### ISSUE TITLE
Add a demo server to the README

### ISSUE THREAD

**Issue by th3m4ri0** [huytd/agar.io-clone#8]
Maybe host it on Heroku (rip free tier) or Openshift ?

**Comment by D3VONT3CH** [comment]
Demo:
http://pillo-nibro.rhcloud.com/

**Comment by huytd** [comment]
Linked with Issue #10 
We will deploy the server to many location and put them all in the readme file.
I would like to close this issue, we will continue discuss in the linked issue :D
