### ISSUE TITLE
Add build system to compile es6

### ISSUE THREAD

**Issue by RemoveIt** [huytd/agar.io-clone#80]
With gulp and babel 
#36

**Comment by RemoveIt** [comment]
I'm taking this

**Comment by RemoveIt** [comment]
I'm creating bin folder and putting there all required stuff idk if it fits to everyone

**Comment by RemoveIt** [comment]
to build everything you need to:
* `npm install gulp -g` (if not installed yet)
* `npm install`
* `gulp build`
* `cd bin`; `cd server`; `node server.js` (I can create task for that for eg. gulp run)

**Comment by RemoveIt** [comment]
Ok I added 'run' task to 'watch' task so `gulp watch` gives you running server with auto restart and file compilation when files will be changed.

**Comment by huytd** [comment]
We can put `gulp`, `gulp-cli` as the dependencies in `package.json`, and `gulp build` or `gulp run` in `postinstall` section, so we only have to run `npm install`, `npm start` and everything will be setting up

**Comment by RemoveIt** [comment]
ok
`npm run postinstall` runs `bower install` and  `gulp build`
`npm start` runs `gulp run`
`npm run watch` runs `gulp watch`
also I have fixed test script if you dont have jshint installed globally

**Comment by huytd** [comment]
The next step will be convert all the code to ES6 :D

**Comment by RemoveIt** [comment]
We need to discuss how to do this

**Comment by danprince** [comment]
Would cast a vote for Babel + Browserify, that way we can start to modularise the frontend code at the same time.

**Comment by RemoveIt** [comment]
I'm not sure if it was good idea to merge my build system to master, rewrite to es6 would take some time and I can't do it alone we should have other branch in main repo for this

**Comment by RemoveIt** [comment]
Also I'll create issue for this rewrite
