### ISSUE TITLE
Bad Server/Client Communication Architecture ?

### ISSUE THREAD

**Issue by yueyoum** [huytd/agar.io-clone#82]
##  1.   player's move need server feedback

first, player send `playerSendTarget` command to server.
then server got it, calculate the new position, and send back the `serverTellPlayerMove` command to this player.

after the server feedback, the player can move.

If there is a big lag between player and server,
the player move will be blocked in a long time.

This should be player move first, then got the server feedback, 
player modify it's position with the server feedback data.

## 2. The server broadcast message immediately

when a player move mouse, 
the server will got a `playerSendTarget` command, and `target` data.

server do some calculate (eat food, or eat other players),
then broadcast `serverUpdateAllPlayers` to all connected players.

This is a bad design. 

If there are 100 players connected to the server.
every player move mouse one times per second.

It means, the server will broadcast 100 times in one seconds.
And every client will got 100 times messages.

This is very overload to both server  and client.

This should be done as the follows:

Server has a tick rate (maybe 10Hz.   10 times per second) to sync the whole game world to all clients.
(AOI.  (area of interest )  are just ignored right now  )

player send `playerSendTarget` to server immediately.
server do calculate, and **NOT** broadcast the message to other clients.

When next server tick comes, then send `serverUpdateAllPlayers` to all clients.

This can avoid the overload of server and client in a high rate  communicate.
Server To Client rate is Fixed to the server tick rate.

**Comment by huytd** [comment]
Awesome feedback :+1: 

But in the problem 2, to running a tick in Javascript we have to use `setTimeout` or `setInterval`, this has been used before to spawn foods every second but it super lag. We should find a better solution to run a tick timer on server side.

**Comment by yueyoum** [comment]
I have played the demo https://agar-io-clone-d3vont3ch.c9.io/ on my laptop (Thinkpad X230)

It cause a high CPU usage.
180~240KiB/s network traffic

I think this is due to the communication method:  server broadcast in every player command.

**Comment by psykzz** [comment]
I disagree with 1.
When testing the original AGAR there was no way for you to take an action if the server was dead. All movement was due to messaging from the server.

The only thing controlled client side was the level of zoom.

With 2. however, i do believe we need to either restrict the information that is being sent. If we cant proceed with a tickrate then limiting to nearby within range or maybe making only messages sent on a 1/10 of a second are actually sent.

So if we are getting requests from 1000's of users, then we only send them to a user, if he is less than 1/10 second. That could be implemented with something like an inverse token bucket.

**Comment by ZeHaxor** [comment]
https://github.com/jhurliman/node-rate-limiter might provide a solution for what we need?

**Comment by yueyoum** [comment]
@psykzz 

Yes, problem 1 is optional.   
Client Move First, is for make client move more smooth.
No need for  waiting server feedback.

**Comment by abalabahaha** [comment]
Oh by the way this was fixed a while ago. Server ticks and updates players independent of their target updates since somewhere around 320ab47 from #221
