### ISSUE TITLE
Make travis to test if code from pull requests is passing jshint

### ISSUE THREAD

**Issue by RemoveIt** [huytd/agar.io-clone#84]
or whatever else we want to test

**Comment by RemoveIt** [comment]
@huytd  I was thinking that there was something wrong in travis file but now I understood that repo dont have webhook for travis

**Comment by huytd** [comment]
I installed Travis, you can check the README.md, there is a Travis build status badge :D

**Comment by huytd** [comment]
It will run everytime we have a push or pull request

**Comment by RemoveIt** [comment]
But there should be status in every pull request if he is passing or no

**Comment by RemoveIt** [comment]
http://blog.travis-ci.com/2012-09-04-pull-requests-just-got-even-more-awesome/

**Comment by RemoveIt** [comment]
I think that in travis file we need to tell which branch travis should test then status of build should appear automaticly in every pull request to that branch

**Comment by huytd** [comment]
Could you made a new pull request? Just for testing, you can edit somewhere in `README.md`

**Comment by huytd** [comment]
It worked! But all the test should be fail now :D We need to fix the remains error with jshint
