### ISSUE TITLE
"node server/server.js" or "npm start" is not working

### ISSUE THREAD

**Issue by nezcafe** [huytd/agar.io-clone#87]
I have all packages (NPM,Socket,Bower, etc.). I think that I installed all of requires correctly. But I get an error like;

>root@xxx:~/agar.io-clone# npm start

> agar-clone@1.0.0 start /root/agar.io-clone
> node server/server.js

>Config file not found!

When I try to write "node server/server.js"

>root@sinankose:~/agar.io-clone# node server/server.js
>-bash: /usr/sbin/node: No such file or directory

Both are not working, what should I do?

**Comment by huytd** [comment]
```
-bash: /usr/sbin/node: No such file or directory
```
May be it was a problem with your `nodejs` installation

Could you run this command?
```
node -v
```

**Comment by huytd** [comment]
OK. Found the problem. 
It's not node problem, but there is a new Config file (`config.yml`)
I fixed it in the latest commit

**Comment by nezcafe** [comment]
Should I clone again?

**Comment by Ariamiro** [comment]
@nezcafe clone, please

**Comment by nezcafe** [comment]
I get an error again;

<code>root@xxx:~/agar.io-clone# node server/server.js</code>

module.js:340
    throw err;

   Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/agar.io-clone/server/server.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by jniles** [comment]
That's good, you are almost there. Rerun npm install and it should work.

**Comment by Ariamiro** [comment]
https://github.com/huytd/agar.io-clone/pull/98

**Comment by nezcafe** [comment]
Doesnt figure out. I get still an error.

**Comment by Ariamiro** [comment]
post the error here

**Comment by nezcafe** [comment]
root@xxx:~/agar.io-clone# node server/server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/agar.io-clone/server/server.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by Ariamiro** [comment]
try this command:

´´´´
npm install js-yaml

´´´´

**Comment by nezcafe** [comment]
root@xxx:~/agar.io-clone# node server/server.js
Config file not found!

**Comment by Ariamiro** [comment]
omg, create a new file in server folder called ``config.yml``

and paste in config.yml:

```
port: 3000
maxSizeMass: 50
maxMoveSpeed: 10
massDecreaseRatio: 1000
foodMass: 1
newFoodPerPlayer: 30
respawnFoodPerPlayer: 1
foodRandomWidth: 500
foodRandomHeight: 500
maxFoodCount: 50
noPlayer: 0
defaultPlayerSize: 10
eatableMassDistance: 5
```

save and start server

**Comment by nezcafe** [comment]
I got it, but again error.

root@sinankose:~/agar.io-clone/server# npm start

> agar-clone@1.0.0 start /root/agar.io-clone
> node server/server.js

listening on *:undefined

**Comment by Ariamiro** [comment]
delete and download this:
https://github.com/Ariamiro/agar.io-clone.git

use command:
```
npm install
```

after, open the server

**Comment by nezcafe** [comment]
I did these;

>root@xxx:~# rm -rf agar.io-clone/
>root@xxx:~# git clone https://github.com/Ariamiro/agar.io-clone.git
>Cloning into 'agar.io-clone'...
>remote: Counting objects: 566, done.
>remote: Compressing objects: 100% (21/21), done.
>remote: Total 566 (delta 6), reused 0 (delta 0), pack-reused 541
>Receiving objects: 100% (566/566), 105.07 KiB | 0 bytes/s, done.
>Resolving deltas: 100% (278/278), done.
>Checking connectivity... done.

Then;
root@xxx:~# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.13.0-27-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.0
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by Ariamiro** [comment]
the npm can't find a package.json, are you in the right folder?

**Comment by nezcafe** [comment]
Yes, I installed now. But start server isnt working.

root@xxx:~/agar.io-clone# npm start

> agar-clone@1.0.0 start /root/agar.io-clone
> node server/server.js


fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'config/config.yml'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/root/agar.io-clone/server/server.js:12:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

npm ERR! Linux 3.13.0-27-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! agar-clone@1.0.0 start: `node server/server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the agar-clone@1.0.0 start script 'node server/server.js'.
npm ERR! This is most likely a problem with the agar-clone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls agar-clone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/agar.io-clone/npm-debug.log

**Comment by Ariamiro** [comment]
go to server and rename config.dist.yml to config.yml

**Comment by nezcafe** [comment]
I did it, but again error :(

root@xxx:~/agar.io-clone# node server/server.js

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'config/config.yml'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Object.<anonymous> (/root/agar.io-clone/server/server.js:12:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
