### ISSUE TITLE
Proper source code structure

### ISSUE THREAD

**Issue by kbariotis** [huytd/agar.io-clone#9]
Shouldn't the code be more structured? What about adding some .editorconfig file and linting/hinting? Would you accept such PRs?

**Comment by IgorAntun** [comment]
Might as well modularize it, ex:
/lib/chat.js, /lib/player.js, /lib/food.js and so on so the project is properly structured.
yeah, something like a config.json to configure initial size, speed, etc. would be great as well.

**Comment by huytd** [comment]
Great! Could you help me resturcture the source as your idea please, @IgorAntun ? :D

**Comment by IgorAntun** [comment]
Ok. I'll see if I can work on that tomorrow.
