### ISSUE TITLE
Spiky 4s in names

### ISSUE THREAD

**Issue by danprince** [huytd/agar.io-clone#94]
If a player's name includes a 4, then it renders with a spike above it. See screenshot. Size varies dependant on cell mass. Not critical, just strange.

![screenshot](http://i.snag.gy/bgC7K.jpg)

**Comment by RemoveIt** [comment]
```ctx.miterLimit = 1; 
ctx.lineJoin = "round";```
should fix

**Comment by IgorAntun** [comment]
@RemoveIt feel free to fix it if you may.

**Comment by RemoveIt** [comment]
@IgorAntun Ok but later I need something to eat :fork_and_knife:

**Comment by IgorAntun** [comment]
Fixed as of #116
