### ISSUE TITLE
Problem with new config system

### ISSUE THREAD

**Issue by Ariamiro** [huytd/agar.io-clone#99]
i am getting a lot of problems with the new config system,

problems like this:
```
npm ERR! agar-clone@1.0.0 postinstall: `./node_modules/bower/bin/bower install && cp server/config.dist.yml server/config.yml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the agar-clone@1.0.0 postinstall script.
npm ERR! This is most likely a problem with the agar-clone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/bower/bin/bower install && cp server/config.dist.yml server/config.yml
npm ERR! You can get their info via:
npm ERR!     npm owner ls agar-clone
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.14.13-c9
npm ERR! command "/home/ubuntu/.nvm/v0.10.35/bin/node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "install"
npm ERR! cwd /home/ubuntu/workspace
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
npm ERR! not ok code 0
```

the yml is the problem?

**Comment by RemoveIt** [comment]
someone forgot add a configuration file to repo

**Comment by themuddfamily2** [comment]
Yeah I saw that the config was missing just make a file in /server/ called config.yml with this content https://github.com/huytd/agar.io-clone/commit/494c762d654034ee290116c7fd746bdfa0be51c6

**Comment by Ariamiro** [comment]
this can fix:
https://github.com/huytd/agar.io-clone/pull/102

**Comment by huytd** [comment]
well... sometimes it's `config.dist.yml` and sometimes it's `config.yml`? @.@ omg omg :D

**Comment by RemoveIt** [comment]
maybe just stay with `config.yml` in `./server`

**Comment by Ariamiro** [comment]
no, the config.dist was renamed to config.yml by npm

**Comment by RemoveIt** [comment]
>no, the config.dist was renamed to config.yml by npm

yes it was renamed by npm script but what was the reason for this renaming idk

**Comment by Ariamiro** [comment]
i don't see any reason, its normal in automation, but useless

**Comment by Ariamiro** [comment]
done, i removed the action
